// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: minio_proxy_svr.proto

package minio_proxy_svr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinioProxySvr_Upload_FullMethodName = "/minio_proxy_svr.MinioProxySvr/Upload"
)

// MinioProxySvrClient is the client API for MinioProxySvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinioProxySvrClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadReq, UploadRsp], error)
}

type minioProxySvrClient struct {
	cc grpc.ClientConnInterface
}

func NewMinioProxySvrClient(cc grpc.ClientConnInterface) MinioProxySvrClient {
	return &minioProxySvrClient{cc}
}

func (c *minioProxySvrClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadReq, UploadRsp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinioProxySvr_ServiceDesc.Streams[0], MinioProxySvr_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadReq, UploadRsp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinioProxySvr_UploadClient = grpc.ClientStreamingClient[UploadReq, UploadRsp]

// MinioProxySvrServer is the server API for MinioProxySvr service.
// All implementations should embed UnimplementedMinioProxySvrServer
// for forward compatibility.
type MinioProxySvrServer interface {
	Upload(grpc.ClientStreamingServer[UploadReq, UploadRsp]) error
}

// UnimplementedMinioProxySvrServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinioProxySvrServer struct{}

func (UnimplementedMinioProxySvrServer) Upload(grpc.ClientStreamingServer[UploadReq, UploadRsp]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedMinioProxySvrServer) testEmbeddedByValue() {}

// UnsafeMinioProxySvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinioProxySvrServer will
// result in compilation errors.
type UnsafeMinioProxySvrServer interface {
	mustEmbedUnimplementedMinioProxySvrServer()
}

func RegisterMinioProxySvrServer(s grpc.ServiceRegistrar, srv MinioProxySvrServer) {
	// If the following call panics, it indicates UnimplementedMinioProxySvrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinioProxySvr_ServiceDesc, srv)
}

func _MinioProxySvr_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MinioProxySvrServer).Upload(&grpc.GenericServerStream[UploadReq, UploadRsp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinioProxySvr_UploadServer = grpc.ClientStreamingServer[UploadReq, UploadRsp]

// MinioProxySvr_ServiceDesc is the grpc.ServiceDesc for MinioProxySvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinioProxySvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minio_proxy_svr.MinioProxySvr",
	HandlerType: (*MinioProxySvrServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _MinioProxySvr_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "minio_proxy_svr.proto",
}
