// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: minio_proxy_svr.proto

package minio_proxy_svr

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UploadObjectReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UploadObjectReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadObjectReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadObjectReqMultiError, or nil if none found.
func (m *UploadObjectReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadObjectReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Bucket

	if utf8.RuneCountInString(m.GetFilename()) < 1 {
		err := UploadObjectReqValidationError{
			field:  "Filename",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetChunk() == nil {
		err := UploadObjectReqValidationError{
			field:  "Chunk",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetChunk()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UploadObjectReqValidationError{
					field:  "Chunk",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UploadObjectReqValidationError{
					field:  "Chunk",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChunk()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UploadObjectReqValidationError{
				field:  "Chunk",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UploadObjectReqMultiError(errors)
	}

	return nil
}

// UploadObjectReqMultiError is an error wrapping multiple validation errors
// returned by UploadObjectReq.ValidateAll() if the designated constraints
// aren't met.
type UploadObjectReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadObjectReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadObjectReqMultiError) AllErrors() []error { return m }

// UploadObjectReqValidationError is the validation error returned by
// UploadObjectReq.Validate if the designated constraints aren't met.
type UploadObjectReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadObjectReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadObjectReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadObjectReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadObjectReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadObjectReqValidationError) ErrorName() string { return "UploadObjectReqValidationError" }

// Error satisfies the builtin error interface
func (e UploadObjectReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadObjectReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadObjectReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadObjectReqValidationError{}

// Validate checks the field values on Chunk with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Chunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Chunk with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ChunkMultiError, or nil if none found.
func (m *Chunk) ValidateAll() error {
	return m.validate(true)
}

func (m *Chunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetData()) < 1 {
		err := ChunkValidationError{
			field:  "Data",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Index

	// no validation rules for IsLast

	if len(errors) > 0 {
		return ChunkMultiError(errors)
	}

	return nil
}

// ChunkMultiError is an error wrapping multiple validation errors returned by
// Chunk.ValidateAll() if the designated constraints aren't met.
type ChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChunkMultiError) AllErrors() []error { return m }

// ChunkValidationError is the validation error returned by Chunk.Validate if
// the designated constraints aren't met.
type ChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChunkValidationError) ErrorName() string { return "ChunkValidationError" }

// Error satisfies the builtin error interface
func (e ChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChunkValidationError{}

// Validate checks the field values on UploadObjectRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UploadObjectRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadObjectRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadObjectRspMultiError, or nil if none found.
func (m *UploadObjectRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadObjectRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	if len(errors) > 0 {
		return UploadObjectRspMultiError(errors)
	}

	return nil
}

// UploadObjectRspMultiError is an error wrapping multiple validation errors
// returned by UploadObjectRsp.ValidateAll() if the designated constraints
// aren't met.
type UploadObjectRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadObjectRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadObjectRspMultiError) AllErrors() []error { return m }

// UploadObjectRspValidationError is the validation error returned by
// UploadObjectRsp.Validate if the designated constraints aren't met.
type UploadObjectRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadObjectRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadObjectRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadObjectRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadObjectRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadObjectRspValidationError) ErrorName() string { return "UploadObjectRspValidationError" }

// Error satisfies the builtin error interface
func (e UploadObjectRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadObjectRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadObjectRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadObjectRspValidationError{}
