// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: blog_common.proto

package blog_common

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ERR_CODE_OK                 ErrCode = 0     // 成功
	ErrCode_ERR_CODE_NETWORK_ERROR      ErrCode = 10001 // 网络错误
	ErrCode_ERR_CODE_INVALID_PARAM      ErrCode = 10002 // 参数错误
	ErrCode_ERR_CODE_NOT_FOUND          ErrCode = 10003 // 资源不存在
	ErrCode_ERR_CODE_USER_NOT_LOGIN     ErrCode = 10004 // 用户未登录
	ErrCode_ERR_CODE_TOKEN_EXPIRED      ErrCode = 10010 // token过期
	ErrCode_ERR_CODE_SEND_CODE_COOLDOWN ErrCode = 10011 // 发送验证码过于频繁
	ErrCode_ERR_CODE_INVALID_CODE       ErrCode = 10012 // 验证码错误
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "ERR_CODE_OK",
		10001: "ERR_CODE_NETWORK_ERROR",
		10002: "ERR_CODE_INVALID_PARAM",
		10003: "ERR_CODE_NOT_FOUND",
		10004: "ERR_CODE_USER_NOT_LOGIN",
		10010: "ERR_CODE_TOKEN_EXPIRED",
		10011: "ERR_CODE_SEND_CODE_COOLDOWN",
		10012: "ERR_CODE_INVALID_CODE",
	}
	ErrCode_value = map[string]int32{
		"ERR_CODE_OK":                 0,
		"ERR_CODE_NETWORK_ERROR":      10001,
		"ERR_CODE_INVALID_PARAM":      10002,
		"ERR_CODE_NOT_FOUND":          10003,
		"ERR_CODE_USER_NOT_LOGIN":     10004,
		"ERR_CODE_TOKEN_EXPIRED":      10010,
		"ERR_CODE_SEND_CODE_COOLDOWN": 10011,
		"ERR_CODE_INVALID_CODE":       10012,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_common_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_blog_common_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_blog_common_proto_rawDescGZIP(), []int{0}
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_blog_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_blog_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_blog_common_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientIp      string                 `protobuf:"bytes,10,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_blog_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_blog_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_blog_common_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Header) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Header) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

var File_blog_common_proto protoreflect.FileDescriptor

const file_blog_common_proto_rawDesc = "" +
	"\n" +
	"\x11blog_common.proto\x12\vblog_common\x1a\x17validate/validate.proto\"\"\n" +
	"\aContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"o\n" +
	"\x06Header\x12)\n" +
	"\vfingerprint\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vfingerprint\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tclient_ip\x18\n" +
	" \x01(\tR\bclientIp*\xe6\x01\n" +
	"\aErrCode\x12\x0f\n" +
	"\vERR_CODE_OK\x10\x00\x12\x1b\n" +
	"\x16ERR_CODE_NETWORK_ERROR\x10\x91N\x12\x1b\n" +
	"\x16ERR_CODE_INVALID_PARAM\x10\x92N\x12\x17\n" +
	"\x12ERR_CODE_NOT_FOUND\x10\x93N\x12\x1c\n" +
	"\x17ERR_CODE_USER_NOT_LOGIN\x10\x94N\x12\x1b\n" +
	"\x16ERR_CODE_TOKEN_EXPIRED\x10\x9aN\x12 \n" +
	"\x1bERR_CODE_SEND_CODE_COOLDOWN\x10\x9bN\x12\x1a\n" +
	"\x15ERR_CODE_INVALID_CODE\x10\x9cNB.Z,github.com/boyapple/grpcprotocol/blog_commonb\x06proto3"

var (
	file_blog_common_proto_rawDescOnce sync.Once
	file_blog_common_proto_rawDescData []byte
)

func file_blog_common_proto_rawDescGZIP() []byte {
	file_blog_common_proto_rawDescOnce.Do(func() {
		file_blog_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_common_proto_rawDesc), len(file_blog_common_proto_rawDesc)))
	})
	return file_blog_common_proto_rawDescData
}

var file_blog_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blog_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blog_common_proto_goTypes = []any{
	(ErrCode)(0),    // 0: blog_common.ErrCode
	(*Context)(nil), // 1: blog_common.Context
	(*Header)(nil),  // 2: blog_common.Header
}
var file_blog_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blog_common_proto_init() }
func file_blog_common_proto_init() {
	if File_blog_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_common_proto_rawDesc), len(file_blog_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blog_common_proto_goTypes,
		DependencyIndexes: file_blog_common_proto_depIdxs,
		EnumInfos:         file_blog_common_proto_enumTypes,
		MessageInfos:      file_blog_common_proto_msgTypes,
	}.Build()
	File_blog_common_proto = out.File
	file_blog_common_proto_goTypes = nil
	file_blog_common_proto_depIdxs = nil
}
