// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: blog_user_svr.proto

package blog_user_svr

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Profile with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Profile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Profile with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProfileMultiError, or nil if none found.
func (m *Profile) ValidateAll() error {
	return m.validate(true)
}

func (m *Profile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if l := utf8.RuneCountInString(m.GetNickname()); l < 1 || l > 20 {
		err := ProfileValidationError{
			field:  "Nickname",
			reason: "value length must be between 1 and 20 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetAvatar()); l < 1 || l > 500 {
		err := ProfileValidationError{
			field:  "Avatar",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Cover

	// no validation rules for Bio

	// no validation rules for Location

	// no validation rules for Job

	// no validation rules for Website

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return ProfileMultiError(errors)
	}

	return nil
}

// ProfileMultiError is an error wrapping multiple validation errors returned
// by Profile.ValidateAll() if the designated constraints aren't met.
type ProfileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfileMultiError) AllErrors() []error { return m }

// ProfileValidationError is the validation error returned by Profile.Validate
// if the designated constraints aren't met.
type ProfileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfileValidationError) ErrorName() string { return "ProfileValidationError" }

// Error satisfies the builtin error interface
func (e ProfileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfileValidationError{}

// Validate checks the field values on Account with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Account) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Account with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AccountMultiError, or nil if none found.
func (m *Account) ValidateAll() error {
	return m.validate(true)
}

func (m *Account) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Username

	// no validation rules for Phone

	// no validation rules for Email

	if len(errors) > 0 {
		return AccountMultiError(errors)
	}

	return nil
}

// AccountMultiError is an error wrapping multiple validation errors returned
// by Account.ValidateAll() if the designated constraints aren't met.
type AccountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccountMultiError) AllErrors() []error { return m }

// AccountValidationError is the validation error returned by Account.Validate
// if the designated constraints aren't met.
type AccountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountValidationError) ErrorName() string { return "AccountValidationError" }

// Error satisfies the builtin error interface
func (e AccountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountValidationError{}

// Validate checks the field values on Device with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Device) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Device with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DeviceMultiError, or nil if none found.
func (m *Device) ValidateAll() error {
	return m.validate(true)
}

func (m *Device) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeviceId

	// no validation rules for Ip

	// no validation rules for Os

	// no validation rules for Browser

	// no validation rules for Country

	// no validation rules for Province

	// no validation rules for City

	// no validation rules for LastActiveTime

	if len(errors) > 0 {
		return DeviceMultiError(errors)
	}

	return nil
}

// DeviceMultiError is an error wrapping multiple validation errors returned by
// Device.ValidateAll() if the designated constraints aren't met.
type DeviceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceMultiError) AllErrors() []error { return m }

// DeviceValidationError is the validation error returned by Device.Validate if
// the designated constraints aren't met.
type DeviceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceValidationError) ErrorName() string { return "DeviceValidationError" }

// Error satisfies the builtin error interface
func (e DeviceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDevice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceValidationError{}

// Validate checks the field values on RegisterReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegisterReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegisterReqMultiError, or
// nil if none found.
func (m *RegisterReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _RegisterReq_AccountType_NotInLookup[m.GetAccountType()]; ok {
		err := RegisterReqValidationError{
			field:  "AccountType",
			reason: "value must not be in list [ACCOUNT_TYPE_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccountType_name[int32(m.GetAccountType())]; !ok {
		err := RegisterReqValidationError{
			field:  "AccountType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProfile() == nil {
		err := RegisterReqValidationError{
			field:  "Profile",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProfile()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterReqValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterReqValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProfile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterReqValidationError{
				field:  "Profile",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetAccount()) < 1 {
		err := RegisterReqValidationError{
			field:  "Account",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterReqMultiError(errors)
	}

	return nil
}

// RegisterReqMultiError is an error wrapping multiple validation errors
// returned by RegisterReq.ValidateAll() if the designated constraints aren't met.
type RegisterReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterReqMultiError) AllErrors() []error { return m }

// RegisterReqValidationError is the validation error returned by
// RegisterReq.Validate if the designated constraints aren't met.
type RegisterReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterReqValidationError) ErrorName() string { return "RegisterReqValidationError" }

// Error satisfies the builtin error interface
func (e RegisterReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterReqValidationError{}

var _RegisterReq_AccountType_NotInLookup = map[AccountType]struct{}{
	0: {},
}

// Validate checks the field values on RegisterRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegisterRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegisterRspMultiError, or
// nil if none found.
func (m *RegisterRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return RegisterRspMultiError(errors)
	}

	return nil
}

// RegisterRspMultiError is an error wrapping multiple validation errors
// returned by RegisterRsp.ValidateAll() if the designated constraints aren't met.
type RegisterRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterRspMultiError) AllErrors() []error { return m }

// RegisterRspValidationError is the validation error returned by
// RegisterRsp.Validate if the designated constraints aren't met.
type RegisterRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRspValidationError) ErrorName() string { return "RegisterRspValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRspValidationError{}

// Validate checks the field values on AuthenticateReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthenticateReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthenticateReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthenticateReqMultiError, or nil if none found.
func (m *AuthenticateReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthenticateReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _AuthenticateReq_AuthType_NotInLookup[m.GetAuthType()]; ok {
		err := AuthenticateReqValidationError{
			field:  "AuthType",
			reason: "value must not be in list [AUTH_TYPE_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AuthType_name[int32(m.GetAuthType())]; !ok {
		err := AuthenticateReqValidationError{
			field:  "AuthType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAccount()) < 1 {
		err := AuthenticateReqValidationError{
			field:  "Account",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Credential

	if len(errors) > 0 {
		return AuthenticateReqMultiError(errors)
	}

	return nil
}

// AuthenticateReqMultiError is an error wrapping multiple validation errors
// returned by AuthenticateReq.ValidateAll() if the designated constraints
// aren't met.
type AuthenticateReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthenticateReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthenticateReqMultiError) AllErrors() []error { return m }

// AuthenticateReqValidationError is the validation error returned by
// AuthenticateReq.Validate if the designated constraints aren't met.
type AuthenticateReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthenticateReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthenticateReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthenticateReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthenticateReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthenticateReqValidationError) ErrorName() string { return "AuthenticateReqValidationError" }

// Error satisfies the builtin error interface
func (e AuthenticateReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthenticateReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthenticateReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthenticateReqValidationError{}

var _AuthenticateReq_AuthType_NotInLookup = map[AuthType]struct{}{
	0: {},
}

// Validate checks the field values on AuthenticateRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthenticateRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthenticateRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthenticateRspMultiError, or nil if none found.
func (m *AuthenticateRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthenticateRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return AuthenticateRspMultiError(errors)
	}

	return nil
}

// AuthenticateRspMultiError is an error wrapping multiple validation errors
// returned by AuthenticateRsp.ValidateAll() if the designated constraints
// aren't met.
type AuthenticateRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthenticateRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthenticateRspMultiError) AllErrors() []error { return m }

// AuthenticateRspValidationError is the validation error returned by
// AuthenticateRsp.Validate if the designated constraints aren't met.
type AuthenticateRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthenticateRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthenticateRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthenticateRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthenticateRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthenticateRspValidationError) ErrorName() string { return "AuthenticateRspValidationError" }

// Error satisfies the builtin error interface
func (e AuthenticateRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthenticateRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthenticateRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthenticateRspValidationError{}

// Validate checks the field values on GetProfileReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetProfileReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProfileReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetProfileReqMultiError, or
// nil if none found.
func (m *GetProfileReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProfileReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() < 1 {
		err := GetProfileReqValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetProfileReqMultiError(errors)
	}

	return nil
}

// GetProfileReqMultiError is an error wrapping multiple validation errors
// returned by GetProfileReq.ValidateAll() if the designated constraints
// aren't met.
type GetProfileReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProfileReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProfileReqMultiError) AllErrors() []error { return m }

// GetProfileReqValidationError is the validation error returned by
// GetProfileReq.Validate if the designated constraints aren't met.
type GetProfileReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProfileReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProfileReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProfileReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProfileReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProfileReqValidationError) ErrorName() string { return "GetProfileReqValidationError" }

// Error satisfies the builtin error interface
func (e GetProfileReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProfileReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProfileReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProfileReqValidationError{}

// Validate checks the field values on GetProfileRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetProfileRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProfileRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetProfileRspMultiError, or
// nil if none found.
func (m *GetProfileRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProfileRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProfile()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetProfileRspValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetProfileRspValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProfile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetProfileRspValidationError{
				field:  "Profile",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetProfileRspMultiError(errors)
	}

	return nil
}

// GetProfileRspMultiError is an error wrapping multiple validation errors
// returned by GetProfileRsp.ValidateAll() if the designated constraints
// aren't met.
type GetProfileRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProfileRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProfileRspMultiError) AllErrors() []error { return m }

// GetProfileRspValidationError is the validation error returned by
// GetProfileRsp.Validate if the designated constraints aren't met.
type GetProfileRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProfileRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProfileRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProfileRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProfileRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProfileRspValidationError) ErrorName() string { return "GetProfileRspValidationError" }

// Error satisfies the builtin error interface
func (e GetProfileRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProfileRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProfileRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProfileRspValidationError{}

// Validate checks the field values on GetAccountReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAccountReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAccountReqMultiError, or
// nil if none found.
func (m *GetAccountReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetAccountReqMultiError(errors)
	}

	return nil
}

// GetAccountReqMultiError is an error wrapping multiple validation errors
// returned by GetAccountReq.ValidateAll() if the designated constraints
// aren't met.
type GetAccountReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountReqMultiError) AllErrors() []error { return m }

// GetAccountReqValidationError is the validation error returned by
// GetAccountReq.Validate if the designated constraints aren't met.
type GetAccountReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountReqValidationError) ErrorName() string { return "GetAccountReqValidationError" }

// Error satisfies the builtin error interface
func (e GetAccountReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountReqValidationError{}

// Validate checks the field values on GetAccountRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAccountRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAccountRspMultiError, or
// nil if none found.
func (m *GetAccountRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAccountRspValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAccountRspValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAccountRspValidationError{
				field:  "Account",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAccountRspMultiError(errors)
	}

	return nil
}

// GetAccountRspMultiError is an error wrapping multiple validation errors
// returned by GetAccountRsp.ValidateAll() if the designated constraints
// aren't met.
type GetAccountRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountRspMultiError) AllErrors() []error { return m }

// GetAccountRspValidationError is the validation error returned by
// GetAccountRsp.Validate if the designated constraints aren't met.
type GetAccountRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountRspValidationError) ErrorName() string { return "GetAccountRspValidationError" }

// Error satisfies the builtin error interface
func (e GetAccountRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountRspValidationError{}

// Validate checks the field values on UpdateProfileReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateProfileReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateProfileReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateProfileReqMultiError, or nil if none found.
func (m *UpdateProfileReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateProfileReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProfile() == nil {
		err := UpdateProfileReqValidationError{
			field:  "Profile",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetProfile()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateProfileReqValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateProfileReqValidationError{
					field:  "Profile",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProfile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateProfileReqValidationError{
				field:  "Profile",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateProfileReqMultiError(errors)
	}

	return nil
}

// UpdateProfileReqMultiError is an error wrapping multiple validation errors
// returned by UpdateProfileReq.ValidateAll() if the designated constraints
// aren't met.
type UpdateProfileReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateProfileReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateProfileReqMultiError) AllErrors() []error { return m }

// UpdateProfileReqValidationError is the validation error returned by
// UpdateProfileReq.Validate if the designated constraints aren't met.
type UpdateProfileReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProfileReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProfileReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProfileReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProfileReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProfileReqValidationError) ErrorName() string { return "UpdateProfileReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateProfileReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProfileReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProfileReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProfileReqValidationError{}

// Validate checks the field values on UpdateProfileRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateProfileRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateProfileRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateProfileRspMultiError, or nil if none found.
func (m *UpdateProfileRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateProfileRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateProfileRspMultiError(errors)
	}

	return nil
}

// UpdateProfileRspMultiError is an error wrapping multiple validation errors
// returned by UpdateProfileRsp.ValidateAll() if the designated constraints
// aren't met.
type UpdateProfileRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateProfileRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateProfileRspMultiError) AllErrors() []error { return m }

// UpdateProfileRspValidationError is the validation error returned by
// UpdateProfileRsp.Validate if the designated constraints aren't met.
type UpdateProfileRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateProfileRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateProfileRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateProfileRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateProfileRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateProfileRspValidationError) ErrorName() string { return "UpdateProfileRspValidationError" }

// Error satisfies the builtin error interface
func (e UpdateProfileRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateProfileRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateProfileRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateProfileRspValidationError{}

// Validate checks the field values on UpdateAccountReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateAccountReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAccountReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateAccountReqMultiError, or nil if none found.
func (m *UpdateAccountReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAccountReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _UpdateAccountReq_OpType_NotInLookup[m.GetOpType()]; ok {
		err := UpdateAccountReqValidationError{
			field:  "OpType",
			reason: "value must not be in list [ACCOUNT_OP_TYPE_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := AccountOpType_name[int32(m.GetOpType())]; !ok {
		err := UpdateAccountReqValidationError{
			field:  "OpType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetNewVal()) < 1 {
		err := UpdateAccountReqValidationError{
			field:  "NewVal",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for OldVal

	if len(errors) > 0 {
		return UpdateAccountReqMultiError(errors)
	}

	return nil
}

// UpdateAccountReqMultiError is an error wrapping multiple validation errors
// returned by UpdateAccountReq.ValidateAll() if the designated constraints
// aren't met.
type UpdateAccountReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAccountReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAccountReqMultiError) AllErrors() []error { return m }

// UpdateAccountReqValidationError is the validation error returned by
// UpdateAccountReq.Validate if the designated constraints aren't met.
type UpdateAccountReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAccountReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAccountReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAccountReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAccountReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAccountReqValidationError) ErrorName() string { return "UpdateAccountReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateAccountReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAccountReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAccountReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAccountReqValidationError{}

var _UpdateAccountReq_OpType_NotInLookup = map[AccountOpType]struct{}{
	0: {},
}

// Validate checks the field values on UpdateAccountRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateAccountRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAccountRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateAccountRspMultiError, or nil if none found.
func (m *UpdateAccountRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAccountRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateAccountRspMultiError(errors)
	}

	return nil
}

// UpdateAccountRspMultiError is an error wrapping multiple validation errors
// returned by UpdateAccountRsp.ValidateAll() if the designated constraints
// aren't met.
type UpdateAccountRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAccountRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAccountRspMultiError) AllErrors() []error { return m }

// UpdateAccountRspValidationError is the validation error returned by
// UpdateAccountRsp.Validate if the designated constraints aren't met.
type UpdateAccountRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAccountRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAccountRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAccountRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAccountRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAccountRspValidationError) ErrorName() string { return "UpdateAccountRspValidationError" }

// Error satisfies the builtin error interface
func (e UpdateAccountRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAccountRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAccountRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAccountRspValidationError{}

// Validate checks the field values on GetUserDevicesReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserDevicesReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserDevicesReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserDevicesReqMultiError, or nil if none found.
func (m *GetUserDevicesReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserDevicesReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := GetUserDevicesReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserDevicesReqMultiError(errors)
	}

	return nil
}

// GetUserDevicesReqMultiError is an error wrapping multiple validation errors
// returned by GetUserDevicesReq.ValidateAll() if the designated constraints
// aren't met.
type GetUserDevicesReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserDevicesReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserDevicesReqMultiError) AllErrors() []error { return m }

// GetUserDevicesReqValidationError is the validation error returned by
// GetUserDevicesReq.Validate if the designated constraints aren't met.
type GetUserDevicesReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserDevicesReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserDevicesReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserDevicesReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserDevicesReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserDevicesReqValidationError) ErrorName() string {
	return "GetUserDevicesReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserDevicesReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserDevicesReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserDevicesReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserDevicesReqValidationError{}

// Validate checks the field values on GetUserDevicesRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserDevicesRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserDevicesRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserDevicesRspMultiError, or nil if none found.
func (m *GetUserDevicesRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserDevicesRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDevices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserDevicesRspValidationError{
						field:  fmt.Sprintf("Devices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserDevicesRspValidationError{
						field:  fmt.Sprintf("Devices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserDevicesRspValidationError{
					field:  fmt.Sprintf("Devices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserDevicesRspMultiError(errors)
	}

	return nil
}

// GetUserDevicesRspMultiError is an error wrapping multiple validation errors
// returned by GetUserDevicesRsp.ValidateAll() if the designated constraints
// aren't met.
type GetUserDevicesRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserDevicesRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserDevicesRspMultiError) AllErrors() []error { return m }

// GetUserDevicesRspValidationError is the validation error returned by
// GetUserDevicesRsp.Validate if the designated constraints aren't met.
type GetUserDevicesRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserDevicesRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserDevicesRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserDevicesRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserDevicesRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserDevicesRspValidationError) ErrorName() string {
	return "GetUserDevicesRspValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserDevicesRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserDevicesRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserDevicesRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserDevicesRspValidationError{}

// Validate checks the field values on ReportReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReportReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReportReqMultiError, or nil
// if none found.
func (m *ReportReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _ReportReq_Action_NotInLookup[m.GetAction()]; ok {
		err := ReportReqValidationError{
			field:  "Action",
			reason: "value must not be in list [USER_ACTION_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := UserAction_name[int32(m.GetAction())]; !ok {
		err := ReportReqValidationError{
			field:  "Action",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Data

	if len(errors) > 0 {
		return ReportReqMultiError(errors)
	}

	return nil
}

// ReportReqMultiError is an error wrapping multiple validation errors returned
// by ReportReq.ValidateAll() if the designated constraints aren't met.
type ReportReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportReqMultiError) AllErrors() []error { return m }

// ReportReqValidationError is the validation error returned by
// ReportReq.Validate if the designated constraints aren't met.
type ReportReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportReqValidationError) ErrorName() string { return "ReportReqValidationError" }

// Error satisfies the builtin error interface
func (e ReportReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportReqValidationError{}

var _ReportReq_Action_NotInLookup = map[UserAction]struct{}{
	0: {},
}

// Validate checks the field values on ReportRsp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReportRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReportRspMultiError, or nil
// if none found.
func (m *ReportRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ReportRspMultiError(errors)
	}

	return nil
}

// ReportRspMultiError is an error wrapping multiple validation errors returned
// by ReportRsp.ValidateAll() if the designated constraints aren't met.
type ReportRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportRspMultiError) AllErrors() []error { return m }

// ReportRspValidationError is the validation error returned by
// ReportRsp.Validate if the designated constraints aren't met.
type ReportRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportRspValidationError) ErrorName() string { return "ReportRspValidationError" }

// Error satisfies the builtin error interface
func (e ReportRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportRspValidationError{}
