// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: blog_user_svr.proto

package blog_user_svr

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户服务错误码 11000-11999 用户错误码
type ErrCode int32

const (
	ErrCode_ERR_CODE_OK               ErrCode = 0     // 成功
	ErrCode_ERR_CODE_USER_EXIST       ErrCode = 11001 // 用户已存在
	ErrCode_ERR_CODE_USER_NOT_EXIST   ErrCode = 11002 // 用户不存在
	ErrCode_ERR_CODE_ACCOUNT_DELETED  ErrCode = 11003 // 账号注销
	ErrCode_ERR_CODE_ACCOUNT_LOCKED   ErrCode = 11004 // 账号锁定
	ErrCode_ERR_CODE_ACCOUNT_DISABLED ErrCode = 11005 // 账号已禁用
	ErrCode_ERR_CODE_PASSWORD_ERROR   ErrCode = 11006 // 密码错误
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "ERR_CODE_OK",
		11001: "ERR_CODE_USER_EXIST",
		11002: "ERR_CODE_USER_NOT_EXIST",
		11003: "ERR_CODE_ACCOUNT_DELETED",
		11004: "ERR_CODE_ACCOUNT_LOCKED",
		11005: "ERR_CODE_ACCOUNT_DISABLED",
		11006: "ERR_CODE_PASSWORD_ERROR",
	}
	ErrCode_value = map[string]int32{
		"ERR_CODE_OK":               0,
		"ERR_CODE_USER_EXIST":       11001,
		"ERR_CODE_USER_NOT_EXIST":   11002,
		"ERR_CODE_ACCOUNT_DELETED":  11003,
		"ERR_CODE_ACCOUNT_LOCKED":   11004,
		"ERR_CODE_ACCOUNT_DISABLED": 11005,
		"ERR_CODE_PASSWORD_ERROR":   11006,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_user_svr_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_blog_user_svr_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{0}
}

// ── 用户行为类型枚举 ─────────────────────────────────────────
type UserAction int32

const (
	UserAction_USER_ACTION_UNSPECIFIED      UserAction = 0
	UserAction_USER_ACTION_LOGIN            UserAction = 1 // 登录
	UserAction_USER_ACTION_PUBLISH_ARTICLE  UserAction = 2 // 发布文章
	UserAction_USER_ACTION_LIKE_ARTICLE     UserAction = 3 // 点赞文章
	UserAction_USER_ACTION_FAVORITE_ARTICLE UserAction = 4 // 收藏文章
	UserAction_USER_ACTION_FOLLOW_USER      UserAction = 5 // 关注用户
	UserAction_USER_ACTION_COMMENT_ARTICLE  UserAction = 6 // 评论文章
	UserAction_USER_ACTION_VIEW_ARTICLE     UserAction = 7 // 阅读文章
	UserAction_USER_ACTION_SHARE_ARTICLE    UserAction = 8 // 分享文章
)

// Enum value maps for UserAction.
var (
	UserAction_name = map[int32]string{
		0: "USER_ACTION_UNSPECIFIED",
		1: "USER_ACTION_LOGIN",
		2: "USER_ACTION_PUBLISH_ARTICLE",
		3: "USER_ACTION_LIKE_ARTICLE",
		4: "USER_ACTION_FAVORITE_ARTICLE",
		5: "USER_ACTION_FOLLOW_USER",
		6: "USER_ACTION_COMMENT_ARTICLE",
		7: "USER_ACTION_VIEW_ARTICLE",
		8: "USER_ACTION_SHARE_ARTICLE",
	}
	UserAction_value = map[string]int32{
		"USER_ACTION_UNSPECIFIED":      0,
		"USER_ACTION_LOGIN":            1,
		"USER_ACTION_PUBLISH_ARTICLE":  2,
		"USER_ACTION_LIKE_ARTICLE":     3,
		"USER_ACTION_FAVORITE_ARTICLE": 4,
		"USER_ACTION_FOLLOW_USER":      5,
		"USER_ACTION_COMMENT_ARTICLE":  6,
		"USER_ACTION_VIEW_ARTICLE":     7,
		"USER_ACTION_SHARE_ARTICLE":    8,
	}
)

func (x UserAction) Enum() *UserAction {
	p := new(UserAction)
	*p = x
	return p
}

func (x UserAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAction) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_user_svr_proto_enumTypes[1].Descriptor()
}

func (UserAction) Type() protoreflect.EnumType {
	return &file_blog_user_svr_proto_enumTypes[1]
}

func (x UserAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAction.Descriptor instead.
func (UserAction) EnumDescriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{1}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0 // 未指定
	AccountStatus_ACCOUNT_STATUS_NORMAL      AccountStatus = 1 // 正常
	AccountStatus_ACCOUNT_STATUS_DISABLED    AccountStatus = 2 // 已禁用
	AccountStatus_ACCOUNT_STATUS_LOCKED      AccountStatus = 3 // 已锁定
	AccountStatus_ACCOUNT_STATUS_DELETED     AccountStatus = 4 // 已注销
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_NORMAL",
		2: "ACCOUNT_STATUS_DISABLED",
		3: "ACCOUNT_STATUS_LOCKED",
		4: "ACCOUNT_STATUS_DELETED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_NORMAL":      1,
		"ACCOUNT_STATUS_DISABLED":    2,
		"ACCOUNT_STATUS_LOCKED":      3,
		"ACCOUNT_STATUS_DELETED":     4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_user_svr_proto_enumTypes[2].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_blog_user_svr_proto_enumTypes[2]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{2}
}

// 认证类型
type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED       AuthType = 0 // 未指定
	AuthType_AUTH_TYPE_USERNAME_PASSWORD AuthType = 1 // 用户名密码
	AuthType_AUTH_TYPE_PHONE_PASSWORD    AuthType = 2 // 手机号密码
	AuthType_AUTH_TYPE_EMAIL_PASSWORD    AuthType = 3 // 邮箱密码
	AuthType_AUTH_TYPE_PHONE_CODE        AuthType = 4 // 手机号验证码
	AuthType_AUTH_TYPE_EMAIL_CODE        AuthType = 5 // 邮箱验证码
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_USERNAME_PASSWORD",
		2: "AUTH_TYPE_PHONE_PASSWORD",
		3: "AUTH_TYPE_EMAIL_PASSWORD",
		4: "AUTH_TYPE_PHONE_CODE",
		5: "AUTH_TYPE_EMAIL_CODE",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED":       0,
		"AUTH_TYPE_USERNAME_PASSWORD": 1,
		"AUTH_TYPE_PHONE_PASSWORD":    2,
		"AUTH_TYPE_EMAIL_PASSWORD":    3,
		"AUTH_TYPE_PHONE_CODE":        4,
		"AUTH_TYPE_EMAIL_CODE":        5,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_user_svr_proto_enumTypes[3].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_blog_user_svr_proto_enumTypes[3]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{3}
}

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0 // 未指定
	AccountType_ACCOUNT_TYPE_USERNAME    AccountType = 1 // 用户名
	AccountType_ACCOUNT_TYPE_PHONE       AccountType = 2 // 手机号
	AccountType_ACCOUNT_TYPE_EMAIL       AccountType = 3 // 邮箱
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_USERNAME",
		2: "ACCOUNT_TYPE_PHONE",
		3: "ACCOUNT_TYPE_EMAIL",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_USERNAME":    1,
		"ACCOUNT_TYPE_PHONE":       2,
		"ACCOUNT_TYPE_EMAIL":       3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_user_svr_proto_enumTypes[4].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_blog_user_svr_proto_enumTypes[4]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{4}
}

// 帐号操作类型
type AccountOpType int32

const (
	AccountOpType_ACCOUNT_OP_TYPE_UNSPECIFIED     AccountOpType = 0 // 未指定
	AccountOpType_ACCOUNT_OP_TYPE_CHANGE_USERNAME AccountOpType = 1 // 修改用户名
	AccountOpType_ACCOUNT_OP_TYPE_UPDATE_PASSWORD AccountOpType = 3 // 修改密码
	AccountOpType_ACCOUNT_OP_TYPE_BIND_PHONE      AccountOpType = 4 // 绑定手机号
	AccountOpType_ACCOUNT_OP_TYPE_REBIND_PHONE    AccountOpType = 5 // 换绑手机号
	AccountOpType_ACCOUNT_OP_TYPE_BIND_EMAIL      AccountOpType = 6 // 绑定邮箱
	AccountOpType_ACCOUNT_OP_TYPE_REBIND_EMAIL    AccountOpType = 7 // 换绑邮箱
	AccountOpType_ACCOUNT_OP_TYPE_RESET_PASSWORD  AccountOpType = 8 // 重置密码（无需旧密码，已通过验证码校验）
)

// Enum value maps for AccountOpType.
var (
	AccountOpType_name = map[int32]string{
		0: "ACCOUNT_OP_TYPE_UNSPECIFIED",
		1: "ACCOUNT_OP_TYPE_CHANGE_USERNAME",
		3: "ACCOUNT_OP_TYPE_UPDATE_PASSWORD",
		4: "ACCOUNT_OP_TYPE_BIND_PHONE",
		5: "ACCOUNT_OP_TYPE_REBIND_PHONE",
		6: "ACCOUNT_OP_TYPE_BIND_EMAIL",
		7: "ACCOUNT_OP_TYPE_REBIND_EMAIL",
		8: "ACCOUNT_OP_TYPE_RESET_PASSWORD",
	}
	AccountOpType_value = map[string]int32{
		"ACCOUNT_OP_TYPE_UNSPECIFIED":     0,
		"ACCOUNT_OP_TYPE_CHANGE_USERNAME": 1,
		"ACCOUNT_OP_TYPE_UPDATE_PASSWORD": 3,
		"ACCOUNT_OP_TYPE_BIND_PHONE":      4,
		"ACCOUNT_OP_TYPE_REBIND_PHONE":    5,
		"ACCOUNT_OP_TYPE_BIND_EMAIL":      6,
		"ACCOUNT_OP_TYPE_REBIND_EMAIL":    7,
		"ACCOUNT_OP_TYPE_RESET_PASSWORD":  8,
	}
)

func (x AccountOpType) Enum() *AccountOpType {
	p := new(AccountOpType)
	*p = x
	return p
}

func (x AccountOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_user_svr_proto_enumTypes[5].Descriptor()
}

func (AccountOpType) Type() protoreflect.EnumType {
	return &file_blog_user_svr_proto_enumTypes[5]
}

func (x AccountOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountOpType.Descriptor instead.
func (AccountOpType) EnumDescriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{5}
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Job           string                 `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Website       string                 `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	CreateTime    int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 注册时间（秒级时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_blog_user_svr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Profile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Profile) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Profile) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Profile) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Profile) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // 用户名（可能为空）
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`       // 手机号（明文，可能为空）
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱（明文，可能为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_blog_user_svr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ip             string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Os             string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Browser        string                 `protobuf:"bytes,5,opt,name=browser,proto3" json:"browser,omitempty"`
	Country        string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Province       string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City           string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	LastActiveTime int64                  `protobuf:"varint,9,opt,name=last_active_time,json=lastActiveTime,proto3" json:"last_active_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_blog_user_svr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Device) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Device) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Device) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Device) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Device) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Device) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountType   AccountType            `protobuf:"varint,1,opt,name=account_type,json=accountType,proto3,enum=blog_user_svr.AccountType" json:"account_type,omitempty"`
	Profile       *Profile               `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_blog_user_svr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *RegisterReq) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RegisterReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type RegisterRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRsp) Reset() {
	*x = RegisterRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRsp) ProtoMessage() {}

func (x *RegisterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRsp.ProtoReflect.Descriptor instead.
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRsp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AuthenticateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      AuthType               `protobuf:"varint,1,opt,name=auth_type,json=authType,proto3,enum=blog_user_svr.AuthType" json:"auth_type,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"` // 密码类型必传；验证码类型由调用方已校验，此处不传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateReq) Reset() {
	*x = AuthenticateReq{}
	mi := &file_blog_user_svr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateReq) ProtoMessage() {}

func (x *AuthenticateReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateReq.ProtoReflect.Descriptor instead.
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateReq) GetAuthType() AuthType {
	if x != nil {
		return x.AuthType
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (x *AuthenticateReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AuthenticateReq) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type AuthenticateRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRsp) Reset() {
	*x = AuthenticateRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRsp) ProtoMessage() {}

func (x *AuthenticateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRsp.ProtoReflect.Descriptor instead.
func (*AuthenticateRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticateRsp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReq) Reset() {
	*x = GetProfileReq{}
	mi := &file_blog_user_svr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReq) ProtoMessage() {}

func (x *GetProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReq.ProtoReflect.Descriptor instead.
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRsp) Reset() {
	*x = GetProfileRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRsp) ProtoMessage() {}

func (x *GetProfileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRsp.ProtoReflect.Descriptor instead.
func (*GetProfileRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileRsp) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetAccountReq 获取用户账号信息请求,只能获取自己的，通过ctx中拿
type GetAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReq) Reset() {
	*x = GetAccountReq{}
	mi := &file_blog_user_svr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReq) ProtoMessage() {}

func (x *GetAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReq.ProtoReflect.Descriptor instead.
func (*GetAccountReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{9}
}

type GetAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRsp) Reset() {
	*x = GetAccountRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRsp) ProtoMessage() {}

func (x *GetAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRsp.ProtoReflect.Descriptor instead.
func (*GetAccountRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{10}
}

func (x *GetAccountRsp) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// UpdateProfileReq 更新用户基本信息请求
type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_blog_user_svr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProfileReq) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRsp) Reset() {
	*x = UpdateProfileRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRsp) ProtoMessage() {}

func (x *UpdateProfileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRsp.ProtoReflect.Descriptor instead.
func (*UpdateProfileRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{12}
}

type UpdateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpType        AccountOpType          `protobuf:"varint,1,opt,name=op_type,json=opType,proto3,enum=blog_user_svr.AccountOpType" json:"op_type,omitempty"`
	NewVal        string                 `protobuf:"bytes,2,opt,name=new_val,json=newVal,proto3" json:"new_val,omitempty"`
	OldVal        string                 `protobuf:"bytes,3,opt,name=old_val,json=oldVal,proto3" json:"old_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountReq) Reset() {
	*x = UpdateAccountReq{}
	mi := &file_blog_user_svr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountReq) ProtoMessage() {}

func (x *UpdateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountReq.ProtoReflect.Descriptor instead.
func (*UpdateAccountReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAccountReq) GetOpType() AccountOpType {
	if x != nil {
		return x.OpType
	}
	return AccountOpType_ACCOUNT_OP_TYPE_UNSPECIFIED
}

func (x *UpdateAccountReq) GetNewVal() string {
	if x != nil {
		return x.NewVal
	}
	return ""
}

func (x *UpdateAccountReq) GetOldVal() string {
	if x != nil {
		return x.OldVal
	}
	return ""
}

type UpdateAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRsp) Reset() {
	*x = UpdateAccountRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRsp) ProtoMessage() {}

func (x *UpdateAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRsp.ProtoReflect.Descriptor instead.
func (*UpdateAccountRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{14}
}

type GetUserDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDevicesReq) Reset() {
	*x = GetUserDevicesReq{}
	mi := &file_blog_user_svr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDevicesReq) ProtoMessage() {}

func (x *GetUserDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDevicesReq.ProtoReflect.Descriptor instead.
func (*GetUserDevicesReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserDevicesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserDevicesRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDevicesRsp) Reset() {
	*x = GetUserDevicesRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDevicesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDevicesRsp) ProtoMessage() {}

func (x *GetUserDevicesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDevicesRsp.ProtoReflect.Descriptor instead.
func (*GetUserDevicesRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserDevicesRsp) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        UserAction             `protobuf:"varint,1,opt,name=action,proto3,enum=blog_user_svr.UserAction" json:"action,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReq) Reset() {
	*x = ReportReq{}
	mi := &file_blog_user_svr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReq) ProtoMessage() {}

func (x *ReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReq.ProtoReflect.Descriptor instead.
func (*ReportReq) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{17}
}

func (x *ReportReq) GetAction() UserAction {
	if x != nil {
		return x.Action
	}
	return UserAction_USER_ACTION_UNSPECIFIED
}

func (x *ReportReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ReportRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRsp) Reset() {
	*x = ReportRsp{}
	mi := &file_blog_user_svr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRsp) ProtoMessage() {}

func (x *ReportRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_user_svr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRsp.ProtoReflect.Descriptor instead.
func (*ReportRsp) Descriptor() ([]byte, []int) {
	return file_blog_user_svr_proto_rawDescGZIP(), []int{18}
}

var File_blog_user_svr_proto protoreflect.FileDescriptor

const file_blog_user_svr_proto_rawDesc = "" +
	"\n" +
	"\x13blog_user_svr.proto\x12\rblog_user_svr\x1a\x17validate/validate.proto\"\xfe\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12%\n" +
	"\bnickname\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x14R\bnickname\x12\"\n" +
	"\x06avatar\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xf4\x03R\x06avatar\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x10\n" +
	"\x03job\x18\a \x01(\tR\x03job\x12\x18\n" +
	"\awebsite\x18\b \x01(\tR\awebsite\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\"j\n" +
	"\aAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\xd3\x01\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x18\n" +
	"\abrowser\x18\x05 \x01(\tR\abrowser\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12(\n" +
	"\x10last_active_time\x18\t \x01(\x03R\x0elastActiveTime\"\xb7\x01\n" +
	"\vRegisterReq\x12I\n" +
	"\faccount_type\x18\x01 \x01(\x0e2\x1a.blog_user_svr.AccountTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\vaccountType\x12:\n" +
	"\aprofile\x18\x02 \x01(\v2\x16.blog_user_svr.ProfileB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aprofile\x12!\n" +
	"\aaccount\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aaccount\"&\n" +
	"\vRegisterRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x96\x01\n" +
	"\x0fAuthenticateReq\x12@\n" +
	"\tauth_type\x18\x01 \x01(\x0e2\x17.blog_user_svr.AuthTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\bauthType\x12!\n" +
	"\aaccount\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aaccount\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\"*\n" +
	"\x0fAuthenticateRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"1\n" +
	"\rGetProfileReq\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02(\x01R\x06userId\"A\n" +
	"\rGetProfileRsp\x120\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.blog_user_svr.ProfileR\aprofile\"\x0f\n" +
	"\rGetAccountReq\"A\n" +
	"\rGetAccountRsp\x120\n" +
	"\aaccount\x18\x01 \x01(\v2\x16.blog_user_svr.AccountR\aaccount\"N\n" +
	"\x10UpdateProfileReq\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.blog_user_svr.ProfileB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aprofile\"\x12\n" +
	"\x10UpdateProfileRsp\"\x90\x01\n" +
	"\x10UpdateAccountReq\x12A\n" +
	"\aop_type\x18\x01 \x01(\x0e2\x1c.blog_user_svr.AccountOpTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06opType\x12 \n" +
	"\anew_val\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06newVal\x12\x17\n" +
	"\aold_val\x18\x03 \x01(\tR\x06oldVal\"\x12\n" +
	"\x10UpdateAccountRsp\"5\n" +
	"\x11GetUserDevicesReq\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\"D\n" +
	"\x11GetUserDevicesRsp\x12/\n" +
	"\adevices\x18\x01 \x03(\v2\x15.blog_user_svr.DeviceR\adevices\"^\n" +
	"\tReportReq\x12=\n" +
	"\x06action\x18\x01 \x01(\x0e2\x19.blog_user_svr.UserActionB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06action\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\v\n" +
	"\tReportRsp*\xcd\x01\n" +
	"\aErrCode\x12\x0f\n" +
	"\vERR_CODE_OK\x10\x00\x12\x18\n" +
	"\x13ERR_CODE_USER_EXIST\x10\xf9U\x12\x1c\n" +
	"\x17ERR_CODE_USER_NOT_EXIST\x10\xfaU\x12\x1d\n" +
	"\x18ERR_CODE_ACCOUNT_DELETED\x10\xfbU\x12\x1c\n" +
	"\x17ERR_CODE_ACCOUNT_LOCKED\x10\xfcU\x12\x1e\n" +
	"\x19ERR_CODE_ACCOUNT_DISABLED\x10\xfdU\x12\x1c\n" +
	"\x17ERR_CODE_PASSWORD_ERROR\x10\xfeU*\x9c\x02\n" +
	"\n" +
	"UserAction\x12\x1b\n" +
	"\x17USER_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11USER_ACTION_LOGIN\x10\x01\x12\x1f\n" +
	"\x1bUSER_ACTION_PUBLISH_ARTICLE\x10\x02\x12\x1c\n" +
	"\x18USER_ACTION_LIKE_ARTICLE\x10\x03\x12 \n" +
	"\x1cUSER_ACTION_FAVORITE_ARTICLE\x10\x04\x12\x1b\n" +
	"\x17USER_ACTION_FOLLOW_USER\x10\x05\x12\x1f\n" +
	"\x1bUSER_ACTION_COMMENT_ARTICLE\x10\x06\x12\x1c\n" +
	"\x18USER_ACTION_VIEW_ARTICLE\x10\a\x12\x1d\n" +
	"\x19USER_ACTION_SHARE_ARTICLE\x10\b*\x9e\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_NORMAL\x10\x01\x12\x1b\n" +
	"\x17ACCOUNT_STATUS_DISABLED\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATUS_LOCKED\x10\x03\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_DELETED\x10\x04*\xb6\x01\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAUTH_TYPE_USERNAME_PASSWORD\x10\x01\x12\x1c\n" +
	"\x18AUTH_TYPE_PHONE_PASSWORD\x10\x02\x12\x1c\n" +
	"\x18AUTH_TYPE_EMAIL_PASSWORD\x10\x03\x12\x18\n" +
	"\x14AUTH_TYPE_PHONE_CODE\x10\x04\x12\x18\n" +
	"\x14AUTH_TYPE_EMAIL_CODE\x10\x05*v\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_TYPE_USERNAME\x10\x01\x12\x16\n" +
	"\x12ACCOUNT_TYPE_PHONE\x10\x02\x12\x16\n" +
	"\x12ACCOUNT_TYPE_EMAIL\x10\x03*\xa2\x02\n" +
	"\rAccountOpType\x12\x1f\n" +
	"\x1bACCOUNT_OP_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fACCOUNT_OP_TYPE_CHANGE_USERNAME\x10\x01\x12#\n" +
	"\x1fACCOUNT_OP_TYPE_UPDATE_PASSWORD\x10\x03\x12\x1e\n" +
	"\x1aACCOUNT_OP_TYPE_BIND_PHONE\x10\x04\x12 \n" +
	"\x1cACCOUNT_OP_TYPE_REBIND_PHONE\x10\x05\x12\x1e\n" +
	"\x1aACCOUNT_OP_TYPE_BIND_EMAIL\x10\x06\x12 \n" +
	"\x1cACCOUNT_OP_TYPE_REBIND_EMAIL\x10\a\x12\"\n" +
	"\x1eACCOUNT_OP_TYPE_RESET_PASSWORD\x10\b2\xef\x04\n" +
	"\vUserService\x12B\n" +
	"\bRegister\x12\x1a.blog_user_svr.RegisterReq\x1a\x1a.blog_user_svr.RegisterRsp\x12N\n" +
	"\fAuthenticate\x12\x1e.blog_user_svr.AuthenticateReq\x1a\x1e.blog_user_svr.AuthenticateRsp\x12H\n" +
	"\n" +
	"GetProfile\x12\x1c.blog_user_svr.GetProfileReq\x1a\x1c.blog_user_svr.GetProfileRsp\x12H\n" +
	"\n" +
	"GetAccount\x12\x1c.blog_user_svr.GetAccountReq\x1a\x1c.blog_user_svr.GetAccountRsp\x12Q\n" +
	"\rUpdateProfile\x12\x1f.blog_user_svr.UpdateProfileReq\x1a\x1f.blog_user_svr.UpdateProfileRsp\x12Q\n" +
	"\rUpdateAccount\x12\x1f.blog_user_svr.UpdateAccountReq\x1a\x1f.blog_user_svr.UpdateAccountRsp\x12T\n" +
	"\x0eGetUserDevices\x12 .blog_user_svr.GetUserDevicesReq\x1a .blog_user_svr.GetUserDevicesRsp\x12<\n" +
	"\x06Report\x12\x18.blog_user_svr.ReportReq\x1a\x18.blog_user_svr.ReportRspB0Z.github.com/boyapple/grpcprotocol/blog_user_svrb\x06proto3"

var (
	file_blog_user_svr_proto_rawDescOnce sync.Once
	file_blog_user_svr_proto_rawDescData []byte
)

func file_blog_user_svr_proto_rawDescGZIP() []byte {
	file_blog_user_svr_proto_rawDescOnce.Do(func() {
		file_blog_user_svr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_user_svr_proto_rawDesc), len(file_blog_user_svr_proto_rawDesc)))
	})
	return file_blog_user_svr_proto_rawDescData
}

var file_blog_user_svr_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_blog_user_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_blog_user_svr_proto_goTypes = []any{
	(ErrCode)(0),              // 0: blog_user_svr.ErrCode
	(UserAction)(0),           // 1: blog_user_svr.UserAction
	(AccountStatus)(0),        // 2: blog_user_svr.AccountStatus
	(AuthType)(0),             // 3: blog_user_svr.AuthType
	(AccountType)(0),          // 4: blog_user_svr.AccountType
	(AccountOpType)(0),        // 5: blog_user_svr.AccountOpType
	(*Profile)(nil),           // 6: blog_user_svr.Profile
	(*Account)(nil),           // 7: blog_user_svr.Account
	(*Device)(nil),            // 8: blog_user_svr.Device
	(*RegisterReq)(nil),       // 9: blog_user_svr.RegisterReq
	(*RegisterRsp)(nil),       // 10: blog_user_svr.RegisterRsp
	(*AuthenticateReq)(nil),   // 11: blog_user_svr.AuthenticateReq
	(*AuthenticateRsp)(nil),   // 12: blog_user_svr.AuthenticateRsp
	(*GetProfileReq)(nil),     // 13: blog_user_svr.GetProfileReq
	(*GetProfileRsp)(nil),     // 14: blog_user_svr.GetProfileRsp
	(*GetAccountReq)(nil),     // 15: blog_user_svr.GetAccountReq
	(*GetAccountRsp)(nil),     // 16: blog_user_svr.GetAccountRsp
	(*UpdateProfileReq)(nil),  // 17: blog_user_svr.UpdateProfileReq
	(*UpdateProfileRsp)(nil),  // 18: blog_user_svr.UpdateProfileRsp
	(*UpdateAccountReq)(nil),  // 19: blog_user_svr.UpdateAccountReq
	(*UpdateAccountRsp)(nil),  // 20: blog_user_svr.UpdateAccountRsp
	(*GetUserDevicesReq)(nil), // 21: blog_user_svr.GetUserDevicesReq
	(*GetUserDevicesRsp)(nil), // 22: blog_user_svr.GetUserDevicesRsp
	(*ReportReq)(nil),         // 23: blog_user_svr.ReportReq
	(*ReportRsp)(nil),         // 24: blog_user_svr.ReportRsp
}
var file_blog_user_svr_proto_depIdxs = []int32{
	4,  // 0: blog_user_svr.RegisterReq.account_type:type_name -> blog_user_svr.AccountType
	6,  // 1: blog_user_svr.RegisterReq.profile:type_name -> blog_user_svr.Profile
	3,  // 2: blog_user_svr.AuthenticateReq.auth_type:type_name -> blog_user_svr.AuthType
	6,  // 3: blog_user_svr.GetProfileRsp.profile:type_name -> blog_user_svr.Profile
	7,  // 4: blog_user_svr.GetAccountRsp.account:type_name -> blog_user_svr.Account
	6,  // 5: blog_user_svr.UpdateProfileReq.profile:type_name -> blog_user_svr.Profile
	5,  // 6: blog_user_svr.UpdateAccountReq.op_type:type_name -> blog_user_svr.AccountOpType
	8,  // 7: blog_user_svr.GetUserDevicesRsp.devices:type_name -> blog_user_svr.Device
	1,  // 8: blog_user_svr.ReportReq.action:type_name -> blog_user_svr.UserAction
	9,  // 9: blog_user_svr.UserService.Register:input_type -> blog_user_svr.RegisterReq
	11, // 10: blog_user_svr.UserService.Authenticate:input_type -> blog_user_svr.AuthenticateReq
	13, // 11: blog_user_svr.UserService.GetProfile:input_type -> blog_user_svr.GetProfileReq
	15, // 12: blog_user_svr.UserService.GetAccount:input_type -> blog_user_svr.GetAccountReq
	17, // 13: blog_user_svr.UserService.UpdateProfile:input_type -> blog_user_svr.UpdateProfileReq
	19, // 14: blog_user_svr.UserService.UpdateAccount:input_type -> blog_user_svr.UpdateAccountReq
	21, // 15: blog_user_svr.UserService.GetUserDevices:input_type -> blog_user_svr.GetUserDevicesReq
	23, // 16: blog_user_svr.UserService.Report:input_type -> blog_user_svr.ReportReq
	10, // 17: blog_user_svr.UserService.Register:output_type -> blog_user_svr.RegisterRsp
	12, // 18: blog_user_svr.UserService.Authenticate:output_type -> blog_user_svr.AuthenticateRsp
	14, // 19: blog_user_svr.UserService.GetProfile:output_type -> blog_user_svr.GetProfileRsp
	16, // 20: blog_user_svr.UserService.GetAccount:output_type -> blog_user_svr.GetAccountRsp
	18, // 21: blog_user_svr.UserService.UpdateProfile:output_type -> blog_user_svr.UpdateProfileRsp
	20, // 22: blog_user_svr.UserService.UpdateAccount:output_type -> blog_user_svr.UpdateAccountRsp
	22, // 23: blog_user_svr.UserService.GetUserDevices:output_type -> blog_user_svr.GetUserDevicesRsp
	24, // 24: blog_user_svr.UserService.Report:output_type -> blog_user_svr.ReportRsp
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_blog_user_svr_proto_init() }
func file_blog_user_svr_proto_init() {
	if File_blog_user_svr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_user_svr_proto_rawDesc), len(file_blog_user_svr_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_user_svr_proto_goTypes,
		DependencyIndexes: file_blog_user_svr_proto_depIdxs,
		EnumInfos:         file_blog_user_svr_proto_enumTypes,
		MessageInfos:      file_blog_user_svr_proto_msgTypes,
	}.Build()
	File_blog_user_svr_proto = out.File
	file_blog_user_svr_proto_goTypes = nil
	file_blog_user_svr_proto_depIdxs = nil
}
