// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: blog_storage_svr.proto

package blog_storage_svr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 分类信息
type CategoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 分类id
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 分类名称
	ParentId   int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`       // 父id
	Priority   int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                       // 优先级,数据越大越靠前
	Icon       string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`                                // 分类图标
	Background string                 `protobuf:"bytes,6,opt,name=background,proto3" json:"background,omitempty"`                    // 分类背景
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新时间
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *CategoryInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CategoryInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CategoryFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CategoryFilter) Reset() {
	*x = CategoryFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFilter) ProtoMessage() {}

func (x *CategoryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFilter.ProtoReflect.Descriptor instead.
func (*CategoryFilter) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryCategoryInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination     *Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	CategoryFilter *CategoryFilter `protobuf:"bytes,2,opt,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"`
}

func (x *QueryCategoryInfoReq) Reset() {
	*x = QueryCategoryInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCategoryInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryInfoReq) ProtoMessage() {}

func (x *QueryCategoryInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryInfoReq.ProtoReflect.Descriptor instead.
func (*QueryCategoryInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{3}
}

func (x *QueryCategoryInfoReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryCategoryInfoReq) GetCategoryFilter() *CategoryFilter {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

type QueryCategoryInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryInfos []*CategoryInfo `protobuf:"bytes,1,rep,name=category_infos,json=categoryInfos,proto3" json:"category_infos,omitempty"`
}

func (x *QueryCategoryInfoRsp) Reset() {
	*x = QueryCategoryInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCategoryInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryInfoRsp) ProtoMessage() {}

func (x *QueryCategoryInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryCategoryInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{4}
}

func (x *QueryCategoryInfoRsp) GetCategoryInfos() []*CategoryInfo {
	if x != nil {
		return x.CategoryInfos
	}
	return nil
}

type GetCategoryInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCategoryInfoReq) Reset() {
	*x = GetCategoryInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryInfoReq) ProtoMessage() {}

func (x *GetCategoryInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryInfoReq.ProtoReflect.Descriptor instead.
func (*GetCategoryInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{5}
}

func (x *GetCategoryInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryInfo *CategoryInfo `protobuf:"bytes,1,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
}

func (x *GetCategoryInfoRsp) Reset() {
	*x = GetCategoryInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryInfoRsp) ProtoMessage() {}

func (x *GetCategoryInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryInfoRsp.ProtoReflect.Descriptor instead.
func (*GetCategoryInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{6}
}

func (x *GetCategoryInfoRsp) GetCategoryInfo() *CategoryInfo {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

type CreateCategoryInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryInfo *CategoryInfo `protobuf:"bytes,1,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
}

func (x *CreateCategoryInfoReq) Reset() {
	*x = CreateCategoryInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCategoryInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryInfoReq) ProtoMessage() {}

func (x *CreateCategoryInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryInfoReq.ProtoReflect.Descriptor instead.
func (*CreateCategoryInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCategoryInfoReq) GetCategoryInfo() *CategoryInfo {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

type CreateCategoryInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCategoryInfoRsp) Reset() {
	*x = CreateCategoryInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCategoryInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryInfoRsp) ProtoMessage() {}

func (x *CreateCategoryInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryInfoRsp.ProtoReflect.Descriptor instead.
func (*CreateCategoryInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{8}
}

type UpdateCategoryInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryInfo *CategoryInfo `protobuf:"bytes,1,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
}

func (x *UpdateCategoryInfoReq) Reset() {
	*x = UpdateCategoryInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCategoryInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryInfoReq) ProtoMessage() {}

func (x *UpdateCategoryInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateCategoryInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCategoryInfoReq) GetCategoryInfo() *CategoryInfo {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

type UpdateCategoryInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCategoryInfoRsp) Reset() {
	*x = UpdateCategoryInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCategoryInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryInfoRsp) ProtoMessage() {}

func (x *UpdateCategoryInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryInfoRsp.ProtoReflect.Descriptor instead.
func (*UpdateCategoryInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{10}
}

// 标签信息
type TagInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 标签id
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 标签名称
	Alias      string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`                              // 标签别名
	Color      string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`                              // 颜色
	Icon       string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`                                // 标签图标
	Background string                 `protobuf:"bytes,6,opt,name=background,proto3" json:"background,omitempty"`                    // 标签背景
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新时间
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{11}
}

func (x *TagInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *TagInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TagInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TagInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *TagInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TagInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// 标签过滤
type TagFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TagFilter) Reset() {
	*x = TagFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFilter) ProtoMessage() {}

func (x *TagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFilter.ProtoReflect.Descriptor instead.
func (*TagFilter) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{12}
}

func (x *TagFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryTagInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	TagFilter  *TagFilter  `protobuf:"bytes,2,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
}

func (x *QueryTagInfoReq) Reset() {
	*x = QueryTagInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTagInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagInfoReq) ProtoMessage() {}

func (x *QueryTagInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagInfoReq.ProtoReflect.Descriptor instead.
func (*QueryTagInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{13}
}

func (x *QueryTagInfoReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryTagInfoReq) GetTagFilter() *TagFilter {
	if x != nil {
		return x.TagFilter
	}
	return nil
}

type QueryTagInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagInfos []*TagInfo `protobuf:"bytes,1,rep,name=tag_infos,json=tagInfos,proto3" json:"tag_infos,omitempty"`
}

func (x *QueryTagInfoRsp) Reset() {
	*x = QueryTagInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTagInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagInfoRsp) ProtoMessage() {}

func (x *QueryTagInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryTagInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{14}
}

func (x *QueryTagInfoRsp) GetTagInfos() []*TagInfo {
	if x != nil {
		return x.TagInfos
	}
	return nil
}

type GetTagInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTagInfoReq) Reset() {
	*x = GetTagInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagInfoReq) ProtoMessage() {}

func (x *GetTagInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagInfoReq.ProtoReflect.Descriptor instead.
func (*GetTagInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{15}
}

func (x *GetTagInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTagInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagInfo *TagInfo `protobuf:"bytes,1,opt,name=tag_info,json=tagInfo,proto3" json:"tag_info,omitempty"`
}

func (x *GetTagInfoRsp) Reset() {
	*x = GetTagInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagInfoRsp) ProtoMessage() {}

func (x *GetTagInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagInfoRsp.ProtoReflect.Descriptor instead.
func (*GetTagInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{16}
}

func (x *GetTagInfoRsp) GetTagInfo() *TagInfo {
	if x != nil {
		return x.TagInfo
	}
	return nil
}

type CreateTagInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagInfo *TagInfo `protobuf:"bytes,1,opt,name=tag_info,json=tagInfo,proto3" json:"tag_info,omitempty"`
}

func (x *CreateTagInfoReq) Reset() {
	*x = CreateTagInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagInfoReq) ProtoMessage() {}

func (x *CreateTagInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagInfoReq.ProtoReflect.Descriptor instead.
func (*CreateTagInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTagInfoReq) GetTagInfo() *TagInfo {
	if x != nil {
		return x.TagInfo
	}
	return nil
}

type CreateTagInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTagInfoRsp) Reset() {
	*x = CreateTagInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagInfoRsp) ProtoMessage() {}

func (x *CreateTagInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagInfoRsp.ProtoReflect.Descriptor instead.
func (*CreateTagInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{18}
}

type UpdateTagInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagInfo *TagInfo `protobuf:"bytes,1,opt,name=tag_info,json=tagInfo,proto3" json:"tag_info,omitempty"`
}

func (x *UpdateTagInfoReq) Reset() {
	*x = UpdateTagInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagInfoReq) ProtoMessage() {}

func (x *UpdateTagInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateTagInfoReq) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateTagInfoReq) GetTagInfo() *TagInfo {
	if x != nil {
		return x.TagInfo
	}
	return nil
}

type UpdateTagInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTagInfoRsp) Reset() {
	*x = UpdateTagInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_storage_svr_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagInfoRsp) ProtoMessage() {}

func (x *UpdateTagInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_storage_svr_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagInfoRsp.ProtoReflect.Descriptor instead.
func (*UpdateTagInfoRsp) Descriptor() ([]byte, []int) {
	return file_blog_storage_svr_proto_rawDescGZIP(), []int{20}
}

var File_blog_storage_svr_proto protoreflect.FileDescriptor

var file_blog_storage_svr_proto_rawDesc = []byte{
	0x0a, 0x16, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0a, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x99, 0x02, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x14, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x49, 0x0a, 0x0f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0e, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x14, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x0e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5c, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x43, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x73, 0x70, 0x22, 0x5c, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x43, 0x0a, 0x0d, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x22, 0x87, 0x02, 0x0a, 0x07, 0x54, 0x61,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0a, 0x74, 0x61, 0x67, 0x5f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x54, 0x61,
	0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x09, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x22, 0x49, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x67, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x54, 0x61, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x1f, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12,
	0x34, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x76, 0x72, 0x2e, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x74, 0x61,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x48, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x08, 0x74, 0x61, 0x67,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x54,
	0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x74, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x73, 0x70, 0x22, 0x48, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x54, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x74, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x12, 0x0a,
	0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73,
	0x70, 0x32, 0xfc, 0x05, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x76, 0x72, 0x12, 0x63, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x26, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x76, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x24, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x66, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70,
	0x12, 0x66, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x27, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x76, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x54, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x4e,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x57,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x22, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x76, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x57, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70,
	0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2e, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x76, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blog_storage_svr_proto_rawDescOnce sync.Once
	file_blog_storage_svr_proto_rawDescData = file_blog_storage_svr_proto_rawDesc
)

func file_blog_storage_svr_proto_rawDescGZIP() []byte {
	file_blog_storage_svr_proto_rawDescOnce.Do(func() {
		file_blog_storage_svr_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_storage_svr_proto_rawDescData)
	})
	return file_blog_storage_svr_proto_rawDescData
}

var file_blog_storage_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_blog_storage_svr_proto_goTypes = []interface{}{
	(*Pagination)(nil),            // 0: blog_storage_svr.Pagination
	(*CategoryInfo)(nil),          // 1: blog_storage_svr.CategoryInfo
	(*CategoryFilter)(nil),        // 2: blog_storage_svr.CategoryFilter
	(*QueryCategoryInfoReq)(nil),  // 3: blog_storage_svr.QueryCategoryInfoReq
	(*QueryCategoryInfoRsp)(nil),  // 4: blog_storage_svr.QueryCategoryInfoRsp
	(*GetCategoryInfoReq)(nil),    // 5: blog_storage_svr.GetCategoryInfoReq
	(*GetCategoryInfoRsp)(nil),    // 6: blog_storage_svr.GetCategoryInfoRsp
	(*CreateCategoryInfoReq)(nil), // 7: blog_storage_svr.CreateCategoryInfoReq
	(*CreateCategoryInfoRsp)(nil), // 8: blog_storage_svr.CreateCategoryInfoRsp
	(*UpdateCategoryInfoReq)(nil), // 9: blog_storage_svr.UpdateCategoryInfoReq
	(*UpdateCategoryInfoRsp)(nil), // 10: blog_storage_svr.UpdateCategoryInfoRsp
	(*TagInfo)(nil),               // 11: blog_storage_svr.TagInfo
	(*TagFilter)(nil),             // 12: blog_storage_svr.TagFilter
	(*QueryTagInfoReq)(nil),       // 13: blog_storage_svr.QueryTagInfoReq
	(*QueryTagInfoRsp)(nil),       // 14: blog_storage_svr.QueryTagInfoRsp
	(*GetTagInfoReq)(nil),         // 15: blog_storage_svr.GetTagInfoReq
	(*GetTagInfoRsp)(nil),         // 16: blog_storage_svr.GetTagInfoRsp
	(*CreateTagInfoReq)(nil),      // 17: blog_storage_svr.CreateTagInfoReq
	(*CreateTagInfoRsp)(nil),      // 18: blog_storage_svr.CreateTagInfoRsp
	(*UpdateTagInfoReq)(nil),      // 19: blog_storage_svr.UpdateTagInfoReq
	(*UpdateTagInfoRsp)(nil),      // 20: blog_storage_svr.UpdateTagInfoRsp
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_blog_storage_svr_proto_depIdxs = []int32{
	21, // 0: blog_storage_svr.CategoryInfo.create_time:type_name -> google.protobuf.Timestamp
	21, // 1: blog_storage_svr.CategoryInfo.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: blog_storage_svr.QueryCategoryInfoReq.pagination:type_name -> blog_storage_svr.Pagination
	2,  // 3: blog_storage_svr.QueryCategoryInfoReq.category_filter:type_name -> blog_storage_svr.CategoryFilter
	1,  // 4: blog_storage_svr.QueryCategoryInfoRsp.category_infos:type_name -> blog_storage_svr.CategoryInfo
	1,  // 5: blog_storage_svr.GetCategoryInfoRsp.category_info:type_name -> blog_storage_svr.CategoryInfo
	1,  // 6: blog_storage_svr.CreateCategoryInfoReq.category_info:type_name -> blog_storage_svr.CategoryInfo
	1,  // 7: blog_storage_svr.UpdateCategoryInfoReq.category_info:type_name -> blog_storage_svr.CategoryInfo
	21, // 8: blog_storage_svr.TagInfo.create_time:type_name -> google.protobuf.Timestamp
	21, // 9: blog_storage_svr.TagInfo.update_time:type_name -> google.protobuf.Timestamp
	0,  // 10: blog_storage_svr.QueryTagInfoReq.pagination:type_name -> blog_storage_svr.Pagination
	12, // 11: blog_storage_svr.QueryTagInfoReq.tag_filter:type_name -> blog_storage_svr.TagFilter
	11, // 12: blog_storage_svr.QueryTagInfoRsp.tag_infos:type_name -> blog_storage_svr.TagInfo
	11, // 13: blog_storage_svr.GetTagInfoRsp.tag_info:type_name -> blog_storage_svr.TagInfo
	11, // 14: blog_storage_svr.CreateTagInfoReq.tag_info:type_name -> blog_storage_svr.TagInfo
	11, // 15: blog_storage_svr.UpdateTagInfoReq.tag_info:type_name -> blog_storage_svr.TagInfo
	3,  // 16: blog_storage_svr.BlogStorageSvr.QueryCategoryInfo:input_type -> blog_storage_svr.QueryCategoryInfoReq
	5,  // 17: blog_storage_svr.BlogStorageSvr.GetCategoryInfo:input_type -> blog_storage_svr.GetCategoryInfoReq
	7,  // 18: blog_storage_svr.BlogStorageSvr.CreateCategoryInfo:input_type -> blog_storage_svr.CreateCategoryInfoReq
	9,  // 19: blog_storage_svr.BlogStorageSvr.UpdateCategoryInfo:input_type -> blog_storage_svr.UpdateCategoryInfoReq
	13, // 20: blog_storage_svr.BlogStorageSvr.QueryTagInfo:input_type -> blog_storage_svr.QueryTagInfoReq
	15, // 21: blog_storage_svr.BlogStorageSvr.GetTagInfo:input_type -> blog_storage_svr.GetTagInfoReq
	17, // 22: blog_storage_svr.BlogStorageSvr.CreateTagInfo:input_type -> blog_storage_svr.CreateTagInfoReq
	19, // 23: blog_storage_svr.BlogStorageSvr.UpdateTagInfo:input_type -> blog_storage_svr.UpdateTagInfoReq
	4,  // 24: blog_storage_svr.BlogStorageSvr.QueryCategoryInfo:output_type -> blog_storage_svr.QueryCategoryInfoRsp
	6,  // 25: blog_storage_svr.BlogStorageSvr.GetCategoryInfo:output_type -> blog_storage_svr.GetCategoryInfoRsp
	8,  // 26: blog_storage_svr.BlogStorageSvr.CreateCategoryInfo:output_type -> blog_storage_svr.CreateCategoryInfoRsp
	10, // 27: blog_storage_svr.BlogStorageSvr.UpdateCategoryInfo:output_type -> blog_storage_svr.UpdateCategoryInfoRsp
	14, // 28: blog_storage_svr.BlogStorageSvr.QueryTagInfo:output_type -> blog_storage_svr.QueryTagInfoRsp
	16, // 29: blog_storage_svr.BlogStorageSvr.GetTagInfo:output_type -> blog_storage_svr.GetTagInfoRsp
	18, // 30: blog_storage_svr.BlogStorageSvr.CreateTagInfo:output_type -> blog_storage_svr.CreateTagInfoRsp
	20, // 31: blog_storage_svr.BlogStorageSvr.UpdateTagInfo:output_type -> blog_storage_svr.UpdateTagInfoRsp
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_blog_storage_svr_proto_init() }
func file_blog_storage_svr_proto_init() {
	if File_blog_storage_svr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blog_storage_svr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCategoryInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCategoryInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCategoryInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCategoryInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCategoryInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCategoryInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTagInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTagInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTagInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_storage_svr_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTagInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_storage_svr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_storage_svr_proto_goTypes,
		DependencyIndexes: file_blog_storage_svr_proto_depIdxs,
		MessageInfos:      file_blog_storage_svr_proto_msgTypes,
	}.Build()
	File_blog_storage_svr_proto = out.File
	file_blog_storage_svr_proto_rawDesc = nil
	file_blog_storage_svr_proto_goTypes = nil
	file_blog_storage_svr_proto_depIdxs = nil
}
