// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: blog_article_svr.proto

package blog_article_svr

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章状态
type ArticleStatus int32

const (
	ArticleStatus_ARTICLE_STATUS_UNKNOWN   ArticleStatus = 0
	ArticleStatus_ARTICLE_STATUS_DRAFT     ArticleStatus = 1 // 草稿
	ArticleStatus_ARTICLE_STATUS_PENDING   ArticleStatus = 2 // 待审核
	ArticleStatus_ARTICLE_STATUS_PUBLISHED ArticleStatus = 3 // 已发布
	ArticleStatus_ARTICLE_STATUS_REJECTED  ArticleStatus = 4 // 已拒绝
	ArticleStatus_ARTICLE_STATUS_OFFLINE   ArticleStatus = 5 // 已下架
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "ARTICLE_STATUS_UNKNOWN",
		1: "ARTICLE_STATUS_DRAFT",
		2: "ARTICLE_STATUS_PENDING",
		3: "ARTICLE_STATUS_PUBLISHED",
		4: "ARTICLE_STATUS_REJECTED",
		5: "ARTICLE_STATUS_OFFLINE",
	}
	ArticleStatus_value = map[string]int32{
		"ARTICLE_STATUS_UNKNOWN":   0,
		"ARTICLE_STATUS_DRAFT":     1,
		"ARTICLE_STATUS_PENDING":   2,
		"ARTICLE_STATUS_PUBLISHED": 3,
		"ARTICLE_STATUS_REJECTED":  4,
		"ARTICLE_STATUS_OFFLINE":   5,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_article_svr_proto_enumTypes[0].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_blog_article_svr_proto_enumTypes[0]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{0}
}

// 文章服务错误码
type ErrCode int32

const (
	ErrCode_ERR_CODE_OK ErrCode = 0
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "ERR_CODE_OK",
	}
	ErrCode_value = map[string]int32{
		"ERR_CODE_OK": 0,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_article_svr_proto_enumTypes[1].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_blog_article_svr_proto_enumTypes[1]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{1}
}

type ArticleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	AuthorId      uint64                 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        ArticleStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=blog_article_svr.ArticleStatus" json:"status,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,20,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Tags          []string               `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleInfo) Reset() {
	*x = ArticleInfo{}
	mi := &file_blog_article_svr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleInfo) ProtoMessage() {}

func (x *ArticleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleInfo.ProtoReflect.Descriptor instead.
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleInfo) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleInfo) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ArticleInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleInfo) GetStatus() ArticleStatus {
	if x != nil {
		return x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNKNOWN
}

func (x *ArticleInfo) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ArticleInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_blog_article_svr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_blog_article_svr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{2}
}

func (x *TagInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TagInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TagInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Feeds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	AuthorId      uint64                 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Slug          string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Cover         string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	AllowComment  bool                   `protobuf:"varint,8,opt,name=allow_comment,json=allowComment,proto3" json:"allow_comment,omitempty"`
	WordCount     uint32                 `protobuf:"varint,9,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,10,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	PublishTime   int64                  `protobuf:"varint,20,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	CreateTime    int64                  `protobuf:"varint,21,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feeds) Reset() {
	*x = Feeds{}
	mi := &file_blog_article_svr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feeds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feeds) ProtoMessage() {}

func (x *Feeds) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feeds.ProtoReflect.Descriptor instead.
func (*Feeds) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{3}
}

func (x *Feeds) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *Feeds) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Feeds) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feeds) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Feeds) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Feeds) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Feeds) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Feeds) GetAllowComment() bool {
	if x != nil {
		return x.AllowComment
	}
	return false
}

func (x *Feeds) GetWordCount() uint32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *Feeds) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Feeds) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *Feeds) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type SaveArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArticleReq) Reset() {
	*x = SaveArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArticleReq) ProtoMessage() {}

func (x *SaveArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArticleReq.ProtoReflect.Descriptor instead.
func (*SaveArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{4}
}

func (x *SaveArticleReq) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type SaveArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArticleRsp) Reset() {
	*x = SaveArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArticleRsp) ProtoMessage() {}

func (x *SaveArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArticleRsp.ProtoReflect.Descriptor instead.
func (*SaveArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{5}
}

func (x *SaveArticleRsp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReq) Reset() {
	*x = GetArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReq) ProtoMessage() {}

func (x *GetArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReq.ProtoReflect.Descriptor instead.
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type GetArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRsp) Reset() {
	*x = GetArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRsp) ProtoMessage() {}

func (x *GetArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRsp.ProtoReflect.Descriptor instead.
func (*GetArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleRsp) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type QueryCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryReq) Reset() {
	*x = QueryCategoryReq{}
	mi := &file_blog_article_svr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryReq) ProtoMessage() {}

func (x *QueryCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryReq.ProtoReflect.Descriptor instead.
func (*QueryCategoryReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{8}
}

type QueryCategoryRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryInfos []*CategoryInfo        `protobuf:"bytes,1,rep,name=category_infos,json=categoryInfos,proto3" json:"category_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryRsp) Reset() {
	*x = QueryCategoryRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryRsp) ProtoMessage() {}

func (x *QueryCategoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryRsp.ProtoReflect.Descriptor instead.
func (*QueryCategoryRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{9}
}

func (x *QueryCategoryRsp) GetCategoryInfos() []*CategoryInfo {
	if x != nil {
		return x.CategoryInfos
	}
	return nil
}

type QueryTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTagReq) Reset() {
	*x = QueryTagReq{}
	mi := &file_blog_article_svr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagReq) ProtoMessage() {}

func (x *QueryTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagReq.ProtoReflect.Descriptor instead.
func (*QueryTagReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{10}
}

func (x *QueryTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryTagRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagInfos      []*TagInfo             `protobuf:"bytes,1,rep,name=tag_infos,json=tagInfos,proto3" json:"tag_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTagRsp) Reset() {
	*x = QueryTagRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTagRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagRsp) ProtoMessage() {}

func (x *QueryTagRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagRsp.ProtoReflect.Descriptor instead.
func (*QueryTagRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTagRsp) GetTagInfos() []*TagInfo {
	if x != nil {
		return x.TagInfos
	}
	return nil
}

var File_blog_article_svr_proto protoreflect.FileDescriptor

const file_blog_article_svr_proto_rawDesc = "" +
	"\n" +
	"\x16blog_article_svr.proto\x12\x10blog_article_svr\x1a\x17validate/validate.proto\"\xa0\x02\n" +
	"\vArticleInfo\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12$\n" +
	"\tauthor_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.blog_article_svr.ArticleStatusR\x06status\x12\x1f\n" +
	"\vcategory_id\x18\x14 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\x15 \x03(\tR\x04tags\"|\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\"y\n" +
	"\aTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"\xe7\x02\n" +
	"\x05Feeds\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x04R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x04R\n" +
	"categoryId\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12#\n" +
	"\rallow_comment\x18\b \x01(\bR\fallowComment\x12\x1d\n" +
	"\n" +
	"word_count\x18\t \x01(\rR\twordCount\x12\x1f\n" +
	"\vis_featured\x18\n" +
	" \x01(\bR\n" +
	"isFeatured\x12!\n" +
	"\fpublish_time\x18\x14 \x01(\x03R\vpublishTime\x12\x1f\n" +
	"\vcreate_time\x18\x15 \x01(\x03R\n" +
	"createTime\"\\\n" +
	"\x0eSaveArticleReq\x12J\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoB\b\xfaB\x05\x8a\x01\x02\x10\x01R\varticleInfo\" \n" +
	"\x0eSaveArticleRsp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\rGetArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"Q\n" +
	"\rGetArticleRsp\x12@\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoR\varticleInfo\"\x12\n" +
	"\x10QueryCategoryReq\"Y\n" +
	"\x10QueryCategoryRsp\x12E\n" +
	"\x0ecategory_infos\x18\x01 \x03(\v2\x1e.blog_article_svr.CategoryInfoR\rcategoryInfos\"!\n" +
	"\vQueryTagReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\vQueryTagRsp\x126\n" +
	"\ttag_infos\x18\x01 \x03(\v2\x19.blog_article_svr.TagInfoR\btagInfos*\xb8\x01\n" +
	"\rArticleStatus\x12\x1a\n" +
	"\x16ARTICLE_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ARTICLE_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16ARTICLE_STATUS_PENDING\x10\x02\x12\x1c\n" +
	"\x18ARTICLE_STATUS_PUBLISHED\x10\x03\x12\x1b\n" +
	"\x17ARTICLE_STATUS_REJECTED\x10\x04\x12\x1a\n" +
	"\x16ARTICLE_STATUS_OFFLINE\x10\x05*\x1a\n" +
	"\aErrCode\x12\x0f\n" +
	"\vERR_CODE_OK\x10\x002\xd6\x02\n" +
	"\x0eArticleService\x12Q\n" +
	"\vSaveArticle\x12 .blog_article_svr.SaveArticleReq\x1a .blog_article_svr.SaveArticleRsp\x12N\n" +
	"\n" +
	"GetArticle\x12\x1f.blog_article_svr.GetArticleReq\x1a\x1f.blog_article_svr.GetArticleRsp\x12W\n" +
	"\rQueryCategory\x12\".blog_article_svr.QueryCategoryReq\x1a\".blog_article_svr.QueryCategoryRsp\x12H\n" +
	"\bQueryTag\x12\x1d.blog_article_svr.QueryTagReq\x1a\x1d.blog_article_svr.QueryTagRspB3Z1github.com/boyapple/grpcprotocol/blog_article_svrb\x06proto3"

var (
	file_blog_article_svr_proto_rawDescOnce sync.Once
	file_blog_article_svr_proto_rawDescData []byte
)

func file_blog_article_svr_proto_rawDescGZIP() []byte {
	file_blog_article_svr_proto_rawDescOnce.Do(func() {
		file_blog_article_svr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_article_svr_proto_rawDesc), len(file_blog_article_svr_proto_rawDesc)))
	})
	return file_blog_article_svr_proto_rawDescData
}

var file_blog_article_svr_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blog_article_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_blog_article_svr_proto_goTypes = []any{
	(ArticleStatus)(0),       // 0: blog_article_svr.ArticleStatus
	(ErrCode)(0),             // 1: blog_article_svr.ErrCode
	(*ArticleInfo)(nil),      // 2: blog_article_svr.ArticleInfo
	(*CategoryInfo)(nil),     // 3: blog_article_svr.CategoryInfo
	(*TagInfo)(nil),          // 4: blog_article_svr.TagInfo
	(*Feeds)(nil),            // 5: blog_article_svr.Feeds
	(*SaveArticleReq)(nil),   // 6: blog_article_svr.SaveArticleReq
	(*SaveArticleRsp)(nil),   // 7: blog_article_svr.SaveArticleRsp
	(*GetArticleReq)(nil),    // 8: blog_article_svr.GetArticleReq
	(*GetArticleRsp)(nil),    // 9: blog_article_svr.GetArticleRsp
	(*QueryCategoryReq)(nil), // 10: blog_article_svr.QueryCategoryReq
	(*QueryCategoryRsp)(nil), // 11: blog_article_svr.QueryCategoryRsp
	(*QueryTagReq)(nil),      // 12: blog_article_svr.QueryTagReq
	(*QueryTagRsp)(nil),      // 13: blog_article_svr.QueryTagRsp
}
var file_blog_article_svr_proto_depIdxs = []int32{
	0,  // 0: blog_article_svr.ArticleInfo.status:type_name -> blog_article_svr.ArticleStatus
	2,  // 1: blog_article_svr.SaveArticleReq.article_info:type_name -> blog_article_svr.ArticleInfo
	2,  // 2: blog_article_svr.GetArticleRsp.article_info:type_name -> blog_article_svr.ArticleInfo
	3,  // 3: blog_article_svr.QueryCategoryRsp.category_infos:type_name -> blog_article_svr.CategoryInfo
	4,  // 4: blog_article_svr.QueryTagRsp.tag_infos:type_name -> blog_article_svr.TagInfo
	6,  // 5: blog_article_svr.ArticleService.SaveArticle:input_type -> blog_article_svr.SaveArticleReq
	8,  // 6: blog_article_svr.ArticleService.GetArticle:input_type -> blog_article_svr.GetArticleReq
	10, // 7: blog_article_svr.ArticleService.QueryCategory:input_type -> blog_article_svr.QueryCategoryReq
	12, // 8: blog_article_svr.ArticleService.QueryTag:input_type -> blog_article_svr.QueryTagReq
	7,  // 9: blog_article_svr.ArticleService.SaveArticle:output_type -> blog_article_svr.SaveArticleRsp
	9,  // 10: blog_article_svr.ArticleService.GetArticle:output_type -> blog_article_svr.GetArticleRsp
	11, // 11: blog_article_svr.ArticleService.QueryCategory:output_type -> blog_article_svr.QueryCategoryRsp
	13, // 12: blog_article_svr.ArticleService.QueryTag:output_type -> blog_article_svr.QueryTagRsp
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_blog_article_svr_proto_init() }
func file_blog_article_svr_proto_init() {
	if File_blog_article_svr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_article_svr_proto_rawDesc), len(file_blog_article_svr_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_article_svr_proto_goTypes,
		DependencyIndexes: file_blog_article_svr_proto_depIdxs,
		EnumInfos:         file_blog_article_svr_proto_enumTypes,
		MessageInfos:      file_blog_article_svr_proto_msgTypes,
	}.Build()
	File_blog_article_svr_proto = out.File
	file_blog_article_svr_proto_goTypes = nil
	file_blog_article_svr_proto_depIdxs = nil
}
