// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: blog_article_svr.proto

package blog_article_svr

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ArticleInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ArticleInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArticleInfoMultiError, or
// nil if none found.
func (m *ArticleInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArticleId

	if m.GetAuthorId() <= 0 {
		err := ArticleInfoValidationError{
			field:  "AuthorId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for Cover

	// no validation rules for Content

	// no validation rules for Status

	// no validation rules for CategoryId

	if len(errors) > 0 {
		return ArticleInfoMultiError(errors)
	}

	return nil
}

// ArticleInfoMultiError is an error wrapping multiple validation errors
// returned by ArticleInfo.ValidateAll() if the designated constraints aren't met.
type ArticleInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleInfoMultiError) AllErrors() []error { return m }

// ArticleInfoValidationError is the validation error returned by
// ArticleInfo.Validate if the designated constraints aren't met.
type ArticleInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleInfoValidationError) ErrorName() string { return "ArticleInfoValidationError" }

// Error satisfies the builtin error interface
func (e ArticleInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleInfoValidationError{}

// Validate checks the field values on Feeds with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Feeds) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Feeds with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FeedsMultiError, or nil if none found.
func (m *Feeds) ValidateAll() error {
	return m.validate(true)
}

func (m *Feeds) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArticleId

	// no validation rules for AuthorId

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for CategoryId

	// no validation rules for Slug

	// no validation rules for Cover

	// no validation rules for AllowComment

	// no validation rules for WordCount

	// no validation rules for IsFeatured

	// no validation rules for PublishTime

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return FeedsMultiError(errors)
	}

	return nil
}

// FeedsMultiError is an error wrapping multiple validation errors returned by
// Feeds.ValidateAll() if the designated constraints aren't met.
type FeedsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FeedsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FeedsMultiError) AllErrors() []error { return m }

// FeedsValidationError is the validation error returned by Feeds.Validate if
// the designated constraints aren't met.
type FeedsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FeedsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FeedsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FeedsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FeedsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FeedsValidationError) ErrorName() string { return "FeedsValidationError" }

// Error satisfies the builtin error interface
func (e FeedsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFeeds.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FeedsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FeedsValidationError{}

// Validate checks the field values on SaveArticleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SaveArticleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SaveArticleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SaveArticleReqMultiError,
// or nil if none found.
func (m *SaveArticleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SaveArticleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetArticleInfo() == nil {
		err := SaveArticleReqValidationError{
			field:  "ArticleInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetArticleInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SaveArticleReqValidationError{
					field:  "ArticleInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SaveArticleReqValidationError{
					field:  "ArticleInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetArticleInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SaveArticleReqValidationError{
				field:  "ArticleInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SaveArticleReqMultiError(errors)
	}

	return nil
}

// SaveArticleReqMultiError is an error wrapping multiple validation errors
// returned by SaveArticleReq.ValidateAll() if the designated constraints
// aren't met.
type SaveArticleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SaveArticleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SaveArticleReqMultiError) AllErrors() []error { return m }

// SaveArticleReqValidationError is the validation error returned by
// SaveArticleReq.Validate if the designated constraints aren't met.
type SaveArticleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SaveArticleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SaveArticleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SaveArticleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SaveArticleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SaveArticleReqValidationError) ErrorName() string { return "SaveArticleReqValidationError" }

// Error satisfies the builtin error interface
func (e SaveArticleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSaveArticleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SaveArticleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SaveArticleReqValidationError{}

// Validate checks the field values on SaveArticleRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SaveArticleRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SaveArticleRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SaveArticleRspMultiError,
// or nil if none found.
func (m *SaveArticleRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *SaveArticleRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SaveArticleRspMultiError(errors)
	}

	return nil
}

// SaveArticleRspMultiError is an error wrapping multiple validation errors
// returned by SaveArticleRsp.ValidateAll() if the designated constraints
// aren't met.
type SaveArticleRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SaveArticleRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SaveArticleRspMultiError) AllErrors() []error { return m }

// SaveArticleRspValidationError is the validation error returned by
// SaveArticleRsp.Validate if the designated constraints aren't met.
type SaveArticleRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SaveArticleRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SaveArticleRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SaveArticleRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SaveArticleRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SaveArticleRspValidationError) ErrorName() string { return "SaveArticleRspValidationError" }

// Error satisfies the builtin error interface
func (e SaveArticleRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSaveArticleRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SaveArticleRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SaveArticleRspValidationError{}

// Validate checks the field values on GetArticleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetArticleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetArticleReqMultiError, or
// nil if none found.
func (m *GetArticleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArticleId

	if len(errors) > 0 {
		return GetArticleReqMultiError(errors)
	}

	return nil
}

// GetArticleReqMultiError is an error wrapping multiple validation errors
// returned by GetArticleReq.ValidateAll() if the designated constraints
// aren't met.
type GetArticleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleReqMultiError) AllErrors() []error { return m }

// GetArticleReqValidationError is the validation error returned by
// GetArticleReq.Validate if the designated constraints aren't met.
type GetArticleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleReqValidationError) ErrorName() string { return "GetArticleReqValidationError" }

// Error satisfies the builtin error interface
func (e GetArticleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleReqValidationError{}

// Validate checks the field values on GetArticleRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetArticleRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetArticleRspMultiError, or
// nil if none found.
func (m *GetArticleRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetArticleInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetArticleRspValidationError{
					field:  "ArticleInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetArticleRspValidationError{
					field:  "ArticleInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetArticleInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetArticleRspValidationError{
				field:  "ArticleInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetArticleRspMultiError(errors)
	}

	return nil
}

// GetArticleRspMultiError is an error wrapping multiple validation errors
// returned by GetArticleRsp.ValidateAll() if the designated constraints
// aren't met.
type GetArticleRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleRspMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleRspMultiError) AllErrors() []error { return m }

// GetArticleRspValidationError is the validation error returned by
// GetArticleRsp.Validate if the designated constraints aren't met.
type GetArticleRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleRspValidationError) ErrorName() string { return "GetArticleRspValidationError" }

// Error satisfies the builtin error interface
func (e GetArticleRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleRspValidationError{}
