// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: blog_article_svr.proto

package blog_article_svr

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章状态,这是草稿表的状态
type ArticleStatus int32

const (
	ArticleStatus_ARTICLE_STATUS_UNKNOWN   ArticleStatus = 0
	ArticleStatus_ARTICLE_STATUS_DRAFT     ArticleStatus = 1 // 草稿
	ArticleStatus_ARTICLE_STATUS_PENDING   ArticleStatus = 2 // 待审核
	ArticleStatus_ARTICLE_STATUS_PUBLISHED ArticleStatus = 3 // 已发布
	ArticleStatus_ARTICLE_STATUS_REJECTED  ArticleStatus = 4 // 已拒绝
	ArticleStatus_ARTICLE_STATUS_OFFLINE   ArticleStatus = 5 // 已下架
)

// Enum value maps for ArticleStatus.
var (
	ArticleStatus_name = map[int32]string{
		0: "ARTICLE_STATUS_UNKNOWN",
		1: "ARTICLE_STATUS_DRAFT",
		2: "ARTICLE_STATUS_PENDING",
		3: "ARTICLE_STATUS_PUBLISHED",
		4: "ARTICLE_STATUS_REJECTED",
		5: "ARTICLE_STATUS_OFFLINE",
	}
	ArticleStatus_value = map[string]int32{
		"ARTICLE_STATUS_UNKNOWN":   0,
		"ARTICLE_STATUS_DRAFT":     1,
		"ARTICLE_STATUS_PENDING":   2,
		"ARTICLE_STATUS_PUBLISHED": 3,
		"ARTICLE_STATUS_REJECTED":  4,
		"ARTICLE_STATUS_OFFLINE":   5,
	}
)

func (x ArticleStatus) Enum() *ArticleStatus {
	p := new(ArticleStatus)
	*p = x
	return p
}

func (x ArticleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_article_svr_proto_enumTypes[0].Descriptor()
}

func (ArticleStatus) Type() protoreflect.EnumType {
	return &file_blog_article_svr_proto_enumTypes[0]
}

func (x ArticleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleStatus.Descriptor instead.
func (ArticleStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{0}
}

// 发布状态,这个是正式表的状态
type PublishStatus int32

const (
	PublishStatus_PUBLISH_STATUS_UNKNOWN PublishStatus = 0
	PublishStatus_PUBLISH_STATUS_PUBLISH PublishStatus = 1 // 已发布
	PublishStatus_PUBLISH_STATUS_OFFLINE PublishStatus = 2 // 已下架
)

// Enum value maps for PublishStatus.
var (
	PublishStatus_name = map[int32]string{
		0: "PUBLISH_STATUS_UNKNOWN",
		1: "PUBLISH_STATUS_PUBLISH",
		2: "PUBLISH_STATUS_OFFLINE",
	}
	PublishStatus_value = map[string]int32{
		"PUBLISH_STATUS_UNKNOWN": 0,
		"PUBLISH_STATUS_PUBLISH": 1,
		"PUBLISH_STATUS_OFFLINE": 2,
	}
)

func (x PublishStatus) Enum() *PublishStatus {
	p := new(PublishStatus)
	*p = x
	return p
}

func (x PublishStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_article_svr_proto_enumTypes[1].Descriptor()
}

func (PublishStatus) Type() protoreflect.EnumType {
	return &file_blog_article_svr_proto_enumTypes[1]
}

func (x PublishStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStatus.Descriptor instead.
func (PublishStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{1}
}

// 文章服务错误码
type ErrCode int32

const (
	ErrCode_ERR_CODE_OK ErrCode = 0
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "ERR_CODE_OK",
	}
	ErrCode_value = map[string]int32{
		"ERR_CODE_OK": 0,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_article_svr_proto_enumTypes[2].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_blog_article_svr_proto_enumTypes[2]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{2}
}

type ArticleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	AuthorId      uint64                 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        ArticleStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=blog_article_svr.ArticleStatus" json:"status,omitempty"`
	AllowComment  bool                   `protobuf:"varint,8,opt,name=allow_comment,json=allowComment,proto3" json:"allow_comment,omitempty"`
	WordCount     uint32                 `protobuf:"varint,9,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,10,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	CategoryInfo  *CategoryInfo          `protobuf:"bytes,20,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
	Tags          []*TagInfo             `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleInfo) Reset() {
	*x = ArticleInfo{}
	mi := &file_blog_article_svr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleInfo) ProtoMessage() {}

func (x *ArticleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleInfo.ProtoReflect.Descriptor instead.
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleInfo) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleInfo) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ArticleInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleInfo) GetStatus() ArticleStatus {
	if x != nil {
		return x.Status
	}
	return ArticleStatus_ARTICLE_STATUS_UNKNOWN
}

func (x *ArticleInfo) GetAllowComment() bool {
	if x != nil {
		return x.AllowComment
	}
	return false
}

func (x *ArticleInfo) GetWordCount() uint32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ArticleInfo) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *ArticleInfo) GetCategoryInfo() *CategoryInfo {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

func (x *ArticleInfo) GetTags() []*TagInfo {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_blog_article_svr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_blog_article_svr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{2}
}

func (x *TagInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TagInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TagInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ArticleCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	AuthorId      uint64                 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Slug          string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Cover         string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	AllowComment  bool                   `protobuf:"varint,8,opt,name=allow_comment,json=allowComment,proto3" json:"allow_comment,omitempty"`
	WordCount     uint32                 `protobuf:"varint,9,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	IsFeatured    bool                   `protobuf:"varint,10,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	PublishStatus PublishStatus          `protobuf:"varint,11,opt,name=publish_status,json=publishStatus,proto3,enum=blog_article_svr.PublishStatus" json:"publish_status,omitempty"`
	PublishTime   int64                  `protobuf:"varint,18,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	CreateTime    int64                  `protobuf:"varint,19,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CategoryInfo  *CategoryInfo          `protobuf:"bytes,21,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
	Tags          []*TagInfo             `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleCard) Reset() {
	*x = ArticleCard{}
	mi := &file_blog_article_svr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleCard) ProtoMessage() {}

func (x *ArticleCard) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleCard.ProtoReflect.Descriptor instead.
func (*ArticleCard) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleCard) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleCard) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleCard) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleCard) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ArticleCard) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ArticleCard) GetAllowComment() bool {
	if x != nil {
		return x.AllowComment
	}
	return false
}

func (x *ArticleCard) GetWordCount() uint32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *ArticleCard) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *ArticleCard) GetPublishStatus() PublishStatus {
	if x != nil {
		return x.PublishStatus
	}
	return PublishStatus_PUBLISH_STATUS_UNKNOWN
}

func (x *ArticleCard) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *ArticleCard) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ArticleCard) GetCategoryInfo() *CategoryInfo {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

func (x *ArticleCard) GetTags() []*TagInfo {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReq) Reset() {
	*x = CreateArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReq) ProtoMessage() {}

func (x *CreateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReq.ProtoReflect.Descriptor instead.
func (*CreateArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{4}
}

func (x *CreateArticleReq) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type CreateArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRsp) Reset() {
	*x = CreateArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRsp) ProtoMessage() {}

func (x *CreateArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRsp.ProtoReflect.Descriptor instead.
func (*CreateArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{5}
}

func (x *CreateArticleRsp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReq) Reset() {
	*x = UpdateArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReq) ProtoMessage() {}

func (x *UpdateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateArticleReq) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type UpdateArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRsp) Reset() {
	*x = UpdateArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRsp) ProtoMessage() {}

func (x *UpdateArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRsp.ProtoReflect.Descriptor instead.
func (*UpdateArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{7}
}

type DeleteArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReq) Reset() {
	*x = DeleteArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReq) ProtoMessage() {}

func (x *DeleteArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReq.ProtoReflect.Descriptor instead.
func (*DeleteArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type DeleteArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRsp) Reset() {
	*x = DeleteArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRsp) ProtoMessage() {}

func (x *DeleteArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRsp.ProtoReflect.Descriptor instead.
func (*DeleteArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{9}
}

type PublishArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleReq) Reset() {
	*x = PublishArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleReq) ProtoMessage() {}

func (x *PublishArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleReq.ProtoReflect.Descriptor instead.
func (*PublishArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{10}
}

func (x *PublishArticleReq) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type PublishArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleRsp) Reset() {
	*x = PublishArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleRsp) ProtoMessage() {}

func (x *PublishArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleRsp.ProtoReflect.Descriptor instead.
func (*PublishArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{11}
}

type OfflineArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineArticleReq) Reset() {
	*x = OfflineArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineArticleReq) ProtoMessage() {}

func (x *OfflineArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineArticleReq.ProtoReflect.Descriptor instead.
func (*OfflineArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{12}
}

func (x *OfflineArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type OfflineArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineArticleRsp) Reset() {
	*x = OfflineArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineArticleRsp) ProtoMessage() {}

func (x *OfflineArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineArticleRsp.ProtoReflect.Descriptor instead.
func (*OfflineArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{13}
}

type GetArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReq) Reset() {
	*x = GetArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReq) ProtoMessage() {}

func (x *GetArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReq.ProtoReflect.Descriptor instead.
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{14}
}

func (x *GetArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type GetArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRsp) Reset() {
	*x = GetArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRsp) ProtoMessage() {}

func (x *GetArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRsp.ProtoReflect.Descriptor instead.
func (*GetArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{15}
}

func (x *GetArticleRsp) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type QueryArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryArticleReq) Reset() {
	*x = QueryArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticleReq) ProtoMessage() {}

func (x *QueryArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticleReq.ProtoReflect.Descriptor instead.
func (*QueryArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{16}
}

type QueryArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   []*ArticleInfo         `protobuf:"bytes,1,rep,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryArticleRsp) Reset() {
	*x = QueryArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticleRsp) ProtoMessage() {}

func (x *QueryArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticleRsp.ProtoReflect.Descriptor instead.
func (*QueryArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{17}
}

func (x *QueryArticleRsp) GetArticleInfo() []*ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type GetFeedsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedsReq) Reset() {
	*x = GetFeedsReq{}
	mi := &file_blog_article_svr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedsReq) ProtoMessage() {}

func (x *GetFeedsReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedsReq.ProtoReflect.Descriptor instead.
func (*GetFeedsReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{18}
}

type GetFeedsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleCards  []*ArticleCard         `protobuf:"bytes,1,rep,name=article_cards,json=articleCards,proto3" json:"article_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedsRsp) Reset() {
	*x = GetFeedsRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedsRsp) ProtoMessage() {}

func (x *GetFeedsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedsRsp.ProtoReflect.Descriptor instead.
func (*GetFeedsRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{19}
}

func (x *GetFeedsRsp) GetArticleCards() []*ArticleCard {
	if x != nil {
		return x.ArticleCards
	}
	return nil
}

type ReadArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArticleReq) Reset() {
	*x = ReadArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArticleReq) ProtoMessage() {}

func (x *ReadArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArticleReq.ProtoReflect.Descriptor instead.
func (*ReadArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{20}
}

func (x *ReadArticleReq) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type ReadArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleInfo   *ArticleInfo           `protobuf:"bytes,1,opt,name=article_info,json=articleInfo,proto3" json:"article_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArticleRsp) Reset() {
	*x = ReadArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArticleRsp) ProtoMessage() {}

func (x *ReadArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArticleRsp.ProtoReflect.Descriptor instead.
func (*ReadArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{21}
}

func (x *ReadArticleRsp) GetArticleInfo() *ArticleInfo {
	if x != nil {
		return x.ArticleInfo
	}
	return nil
}

type SearchArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ScrollId      string                 `protobuf:"bytes,2,opt,name=scroll_id,json=scrollId,proto3" json:"scroll_id,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticleReq) Reset() {
	*x = SearchArticleReq{}
	mi := &file_blog_article_svr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticleReq) ProtoMessage() {}

func (x *SearchArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticleReq.ProtoReflect.Descriptor instead.
func (*SearchArticleReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{22}
}

func (x *SearchArticleReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchArticleReq) GetScrollId() string {
	if x != nil {
		return x.ScrollId
	}
	return ""
}

func (x *SearchArticleReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchArticleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleCards  []*ArticleCard         `protobuf:"bytes,1,rep,name=article_cards,json=articleCards,proto3" json:"article_cards,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ScrollId      string                 `protobuf:"bytes,3,opt,name=scroll_id,json=scrollId,proto3" json:"scroll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticleRsp) Reset() {
	*x = SearchArticleRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticleRsp) ProtoMessage() {}

func (x *SearchArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticleRsp.ProtoReflect.Descriptor instead.
func (*SearchArticleRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{23}
}

func (x *SearchArticleRsp) GetArticleCards() []*ArticleCard {
	if x != nil {
		return x.ArticleCards
	}
	return nil
}

func (x *SearchArticleRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchArticleRsp) GetScrollId() string {
	if x != nil {
		return x.ScrollId
	}
	return ""
}

type QueryCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryReq) Reset() {
	*x = QueryCategoryReq{}
	mi := &file_blog_article_svr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryReq) ProtoMessage() {}

func (x *QueryCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryReq.ProtoReflect.Descriptor instead.
func (*QueryCategoryReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{24}
}

type QueryCategoryRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryInfos []*CategoryInfo        `protobuf:"bytes,1,rep,name=category_infos,json=categoryInfos,proto3" json:"category_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryRsp) Reset() {
	*x = QueryCategoryRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryRsp) ProtoMessage() {}

func (x *QueryCategoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryRsp.ProtoReflect.Descriptor instead.
func (*QueryCategoryRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{25}
}

func (x *QueryCategoryRsp) GetCategoryInfos() []*CategoryInfo {
	if x != nil {
		return x.CategoryInfos
	}
	return nil
}

type QueryTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTagReq) Reset() {
	*x = QueryTagReq{}
	mi := &file_blog_article_svr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagReq) ProtoMessage() {}

func (x *QueryTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagReq.ProtoReflect.Descriptor instead.
func (*QueryTagReq) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{26}
}

func (x *QueryTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryTagRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagInfos      []*TagInfo             `protobuf:"bytes,1,rep,name=tag_infos,json=tagInfos,proto3" json:"tag_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTagRsp) Reset() {
	*x = QueryTagRsp{}
	mi := &file_blog_article_svr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTagRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTagRsp) ProtoMessage() {}

func (x *QueryTagRsp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_article_svr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTagRsp.ProtoReflect.Descriptor instead.
func (*QueryTagRsp) Descriptor() ([]byte, []int) {
	return file_blog_article_svr_proto_rawDescGZIP(), []int{27}
}

func (x *QueryTagRsp) GetTagInfos() []*TagInfo {
	if x != nil {
		return x.TagInfos
	}
	return nil
}

var File_blog_article_svr_proto protoreflect.FileDescriptor

const file_blog_article_svr_proto_rawDesc = "" +
	"\n" +
	"\x16blog_article_svr.proto\x12\x10blog_article_svr\x1a\x17validate/validate.proto\"\xc4\x03\n" +
	"\vArticleInfo\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12$\n" +
	"\tauthor_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.blog_article_svr.ArticleStatusR\x06status\x12#\n" +
	"\rallow_comment\x18\b \x01(\bR\fallowComment\x12\x1d\n" +
	"\n" +
	"word_count\x18\t \x01(\rR\twordCount\x12\x1f\n" +
	"\vis_featured\x18\n" +
	" \x01(\bR\n" +
	"isFeatured\x12C\n" +
	"\rcategory_info\x18\x14 \x01(\v2\x1e.blog_article_svr.CategoryInfoR\fcategoryInfo\x12-\n" +
	"\x04tags\x18\x15 \x03(\v2\x19.blog_article_svr.TagInfoR\x04tags\"|\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\"y\n" +
	"\aTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"\x88\x04\n" +
	"\vArticleCard\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x04R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12#\n" +
	"\rallow_comment\x18\b \x01(\bR\fallowComment\x12\x1d\n" +
	"\n" +
	"word_count\x18\t \x01(\rR\twordCount\x12\x1f\n" +
	"\vis_featured\x18\n" +
	" \x01(\bR\n" +
	"isFeatured\x12F\n" +
	"\x0epublish_status\x18\v \x01(\x0e2\x1f.blog_article_svr.PublishStatusR\rpublishStatus\x12!\n" +
	"\fpublish_time\x18\x12 \x01(\x03R\vpublishTime\x12\x1f\n" +
	"\vcreate_time\x18\x13 \x01(\x03R\n" +
	"createTime\x12C\n" +
	"\rcategory_info\x18\x15 \x01(\v2\x1e.blog_article_svr.CategoryInfoR\fcategoryInfo\x12-\n" +
	"\x04tags\x18\x16 \x03(\v2\x19.blog_article_svr.TagInfoR\x04tags\"^\n" +
	"\x10CreateArticleReq\x12J\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoB\b\xfaB\x05\x8a\x01\x02\x10\x01R\varticleInfo\"\"\n" +
	"\x10CreateArticleRsp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x10UpdateArticleReq\x12J\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoB\b\xfaB\x05\x8a\x01\x02\x10\x01R\varticleInfo\"\x12\n" +
	"\x10UpdateArticleRsp\"1\n" +
	"\x10DeleteArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"\x12\n" +
	"\x10DeleteArticleRsp\"_\n" +
	"\x11PublishArticleReq\x12J\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoB\b\xfaB\x05\x8a\x01\x02\x10\x01R\varticleInfo\"\x13\n" +
	"\x11PublishArticleRsp\"2\n" +
	"\x11OfflineArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"\x13\n" +
	"\x11OfflineArticleRsp\".\n" +
	"\rGetArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"Q\n" +
	"\rGetArticleRsp\x12@\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoR\varticleInfo\"\x11\n" +
	"\x0fQueryArticleReq\"S\n" +
	"\x0fQueryArticleRsp\x12@\n" +
	"\farticle_info\x18\x01 \x03(\v2\x1d.blog_article_svr.ArticleInfoR\varticleInfo\"\r\n" +
	"\vGetFeedsReq\"Q\n" +
	"\vGetFeedsRsp\x12B\n" +
	"\rarticle_cards\x18\x01 \x03(\v2\x1d.blog_article_svr.ArticleCardR\farticleCards\"/\n" +
	"\x0eReadArticleReq\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"R\n" +
	"\x0eReadArticleRsp\x12@\n" +
	"\farticle_info\x18\x01 \x01(\v2\x1d.blog_article_svr.ArticleInfoR\varticleInfo\"]\n" +
	"\x10SearchArticleReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1b\n" +
	"\tscroll_id\x18\x02 \x01(\tR\bscrollId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"\x8e\x01\n" +
	"\x10SearchArticleRsp\x12B\n" +
	"\rarticle_cards\x18\x01 \x03(\v2\x1d.blog_article_svr.ArticleCardR\farticleCards\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1b\n" +
	"\tscroll_id\x18\x03 \x01(\tR\bscrollId\"\x12\n" +
	"\x10QueryCategoryReq\"Y\n" +
	"\x10QueryCategoryRsp\x12E\n" +
	"\x0ecategory_infos\x18\x01 \x03(\v2\x1e.blog_article_svr.CategoryInfoR\rcategoryInfos\"!\n" +
	"\vQueryTagReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\vQueryTagRsp\x126\n" +
	"\ttag_infos\x18\x01 \x03(\v2\x19.blog_article_svr.TagInfoR\btagInfos*\xb8\x01\n" +
	"\rArticleStatus\x12\x1a\n" +
	"\x16ARTICLE_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ARTICLE_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16ARTICLE_STATUS_PENDING\x10\x02\x12\x1c\n" +
	"\x18ARTICLE_STATUS_PUBLISHED\x10\x03\x12\x1b\n" +
	"\x17ARTICLE_STATUS_REJECTED\x10\x04\x12\x1a\n" +
	"\x16ARTICLE_STATUS_OFFLINE\x10\x05*c\n" +
	"\rPublishStatus\x12\x1a\n" +
	"\x16PUBLISH_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16PUBLISH_STATUS_PUBLISH\x10\x01\x12\x1a\n" +
	"\x16PUBLISH_STATUS_OFFLINE\x10\x02*\x1a\n" +
	"\aErrCode\x12\x0f\n" +
	"\vERR_CODE_OK\x10\x002\x92\b\n" +
	"\x0eArticleService\x12W\n" +
	"\rCreateArticle\x12\".blog_article_svr.CreateArticleReq\x1a\".blog_article_svr.CreateArticleRsp\x12W\n" +
	"\rUpdateArticle\x12\".blog_article_svr.UpdateArticleReq\x1a\".blog_article_svr.UpdateArticleRsp\x12W\n" +
	"\rDeleteArticle\x12\".blog_article_svr.DeleteArticleReq\x1a\".blog_article_svr.DeleteArticleRsp\x12N\n" +
	"\n" +
	"GetArticle\x12\x1f.blog_article_svr.GetArticleReq\x1a\x1f.blog_article_svr.GetArticleRsp\x12T\n" +
	"\fQueryArticle\x12!.blog_article_svr.QueryArticleReq\x1a!.blog_article_svr.QueryArticleRsp\x12Z\n" +
	"\x0ePublishArticle\x12#.blog_article_svr.PublishArticleReq\x1a#.blog_article_svr.PublishArticleRsp\x12Z\n" +
	"\x0eOfflineArticle\x12#.blog_article_svr.OfflineArticleReq\x1a#.blog_article_svr.OfflineArticleRsp\x12H\n" +
	"\bGetFeeds\x12\x1d.blog_article_svr.GetFeedsReq\x1a\x1d.blog_article_svr.GetFeedsRsp\x12Q\n" +
	"\vReadArticle\x12 .blog_article_svr.ReadArticleReq\x1a .blog_article_svr.ReadArticleRsp\x12W\n" +
	"\rSearchArticle\x12\".blog_article_svr.SearchArticleReq\x1a\".blog_article_svr.SearchArticleRsp\x12W\n" +
	"\rQueryCategory\x12\".blog_article_svr.QueryCategoryReq\x1a\".blog_article_svr.QueryCategoryRsp\x12H\n" +
	"\bQueryTag\x12\x1d.blog_article_svr.QueryTagReq\x1a\x1d.blog_article_svr.QueryTagRspB3Z1github.com/boyapple/grpcprotocol/blog_article_svrb\x06proto3"

var (
	file_blog_article_svr_proto_rawDescOnce sync.Once
	file_blog_article_svr_proto_rawDescData []byte
)

func file_blog_article_svr_proto_rawDescGZIP() []byte {
	file_blog_article_svr_proto_rawDescOnce.Do(func() {
		file_blog_article_svr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_article_svr_proto_rawDesc), len(file_blog_article_svr_proto_rawDesc)))
	})
	return file_blog_article_svr_proto_rawDescData
}

var file_blog_article_svr_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blog_article_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_blog_article_svr_proto_goTypes = []any{
	(ArticleStatus)(0),        // 0: blog_article_svr.ArticleStatus
	(PublishStatus)(0),        // 1: blog_article_svr.PublishStatus
	(ErrCode)(0),              // 2: blog_article_svr.ErrCode
	(*ArticleInfo)(nil),       // 3: blog_article_svr.ArticleInfo
	(*CategoryInfo)(nil),      // 4: blog_article_svr.CategoryInfo
	(*TagInfo)(nil),           // 5: blog_article_svr.TagInfo
	(*ArticleCard)(nil),       // 6: blog_article_svr.ArticleCard
	(*CreateArticleReq)(nil),  // 7: blog_article_svr.CreateArticleReq
	(*CreateArticleRsp)(nil),  // 8: blog_article_svr.CreateArticleRsp
	(*UpdateArticleReq)(nil),  // 9: blog_article_svr.UpdateArticleReq
	(*UpdateArticleRsp)(nil),  // 10: blog_article_svr.UpdateArticleRsp
	(*DeleteArticleReq)(nil),  // 11: blog_article_svr.DeleteArticleReq
	(*DeleteArticleRsp)(nil),  // 12: blog_article_svr.DeleteArticleRsp
	(*PublishArticleReq)(nil), // 13: blog_article_svr.PublishArticleReq
	(*PublishArticleRsp)(nil), // 14: blog_article_svr.PublishArticleRsp
	(*OfflineArticleReq)(nil), // 15: blog_article_svr.OfflineArticleReq
	(*OfflineArticleRsp)(nil), // 16: blog_article_svr.OfflineArticleRsp
	(*GetArticleReq)(nil),     // 17: blog_article_svr.GetArticleReq
	(*GetArticleRsp)(nil),     // 18: blog_article_svr.GetArticleRsp
	(*QueryArticleReq)(nil),   // 19: blog_article_svr.QueryArticleReq
	(*QueryArticleRsp)(nil),   // 20: blog_article_svr.QueryArticleRsp
	(*GetFeedsReq)(nil),       // 21: blog_article_svr.GetFeedsReq
	(*GetFeedsRsp)(nil),       // 22: blog_article_svr.GetFeedsRsp
	(*ReadArticleReq)(nil),    // 23: blog_article_svr.ReadArticleReq
	(*ReadArticleRsp)(nil),    // 24: blog_article_svr.ReadArticleRsp
	(*SearchArticleReq)(nil),  // 25: blog_article_svr.SearchArticleReq
	(*SearchArticleRsp)(nil),  // 26: blog_article_svr.SearchArticleRsp
	(*QueryCategoryReq)(nil),  // 27: blog_article_svr.QueryCategoryReq
	(*QueryCategoryRsp)(nil),  // 28: blog_article_svr.QueryCategoryRsp
	(*QueryTagReq)(nil),       // 29: blog_article_svr.QueryTagReq
	(*QueryTagRsp)(nil),       // 30: blog_article_svr.QueryTagRsp
}
var file_blog_article_svr_proto_depIdxs = []int32{
	0,  // 0: blog_article_svr.ArticleInfo.status:type_name -> blog_article_svr.ArticleStatus
	4,  // 1: blog_article_svr.ArticleInfo.category_info:type_name -> blog_article_svr.CategoryInfo
	5,  // 2: blog_article_svr.ArticleInfo.tags:type_name -> blog_article_svr.TagInfo
	1,  // 3: blog_article_svr.ArticleCard.publish_status:type_name -> blog_article_svr.PublishStatus
	4,  // 4: blog_article_svr.ArticleCard.category_info:type_name -> blog_article_svr.CategoryInfo
	5,  // 5: blog_article_svr.ArticleCard.tags:type_name -> blog_article_svr.TagInfo
	3,  // 6: blog_article_svr.CreateArticleReq.article_info:type_name -> blog_article_svr.ArticleInfo
	3,  // 7: blog_article_svr.UpdateArticleReq.article_info:type_name -> blog_article_svr.ArticleInfo
	3,  // 8: blog_article_svr.PublishArticleReq.article_info:type_name -> blog_article_svr.ArticleInfo
	3,  // 9: blog_article_svr.GetArticleRsp.article_info:type_name -> blog_article_svr.ArticleInfo
	3,  // 10: blog_article_svr.QueryArticleRsp.article_info:type_name -> blog_article_svr.ArticleInfo
	6,  // 11: blog_article_svr.GetFeedsRsp.article_cards:type_name -> blog_article_svr.ArticleCard
	3,  // 12: blog_article_svr.ReadArticleRsp.article_info:type_name -> blog_article_svr.ArticleInfo
	6,  // 13: blog_article_svr.SearchArticleRsp.article_cards:type_name -> blog_article_svr.ArticleCard
	4,  // 14: blog_article_svr.QueryCategoryRsp.category_infos:type_name -> blog_article_svr.CategoryInfo
	5,  // 15: blog_article_svr.QueryTagRsp.tag_infos:type_name -> blog_article_svr.TagInfo
	7,  // 16: blog_article_svr.ArticleService.CreateArticle:input_type -> blog_article_svr.CreateArticleReq
	9,  // 17: blog_article_svr.ArticleService.UpdateArticle:input_type -> blog_article_svr.UpdateArticleReq
	11, // 18: blog_article_svr.ArticleService.DeleteArticle:input_type -> blog_article_svr.DeleteArticleReq
	17, // 19: blog_article_svr.ArticleService.GetArticle:input_type -> blog_article_svr.GetArticleReq
	19, // 20: blog_article_svr.ArticleService.QueryArticle:input_type -> blog_article_svr.QueryArticleReq
	13, // 21: blog_article_svr.ArticleService.PublishArticle:input_type -> blog_article_svr.PublishArticleReq
	15, // 22: blog_article_svr.ArticleService.OfflineArticle:input_type -> blog_article_svr.OfflineArticleReq
	21, // 23: blog_article_svr.ArticleService.GetFeeds:input_type -> blog_article_svr.GetFeedsReq
	23, // 24: blog_article_svr.ArticleService.ReadArticle:input_type -> blog_article_svr.ReadArticleReq
	25, // 25: blog_article_svr.ArticleService.SearchArticle:input_type -> blog_article_svr.SearchArticleReq
	27, // 26: blog_article_svr.ArticleService.QueryCategory:input_type -> blog_article_svr.QueryCategoryReq
	29, // 27: blog_article_svr.ArticleService.QueryTag:input_type -> blog_article_svr.QueryTagReq
	8,  // 28: blog_article_svr.ArticleService.CreateArticle:output_type -> blog_article_svr.CreateArticleRsp
	10, // 29: blog_article_svr.ArticleService.UpdateArticle:output_type -> blog_article_svr.UpdateArticleRsp
	12, // 30: blog_article_svr.ArticleService.DeleteArticle:output_type -> blog_article_svr.DeleteArticleRsp
	18, // 31: blog_article_svr.ArticleService.GetArticle:output_type -> blog_article_svr.GetArticleRsp
	20, // 32: blog_article_svr.ArticleService.QueryArticle:output_type -> blog_article_svr.QueryArticleRsp
	14, // 33: blog_article_svr.ArticleService.PublishArticle:output_type -> blog_article_svr.PublishArticleRsp
	16, // 34: blog_article_svr.ArticleService.OfflineArticle:output_type -> blog_article_svr.OfflineArticleRsp
	22, // 35: blog_article_svr.ArticleService.GetFeeds:output_type -> blog_article_svr.GetFeedsRsp
	24, // 36: blog_article_svr.ArticleService.ReadArticle:output_type -> blog_article_svr.ReadArticleRsp
	26, // 37: blog_article_svr.ArticleService.SearchArticle:output_type -> blog_article_svr.SearchArticleRsp
	28, // 38: blog_article_svr.ArticleService.QueryCategory:output_type -> blog_article_svr.QueryCategoryRsp
	30, // 39: blog_article_svr.ArticleService.QueryTag:output_type -> blog_article_svr.QueryTagRsp
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_blog_article_svr_proto_init() }
func file_blog_article_svr_proto_init() {
	if File_blog_article_svr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_article_svr_proto_rawDesc), len(file_blog_article_svr_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_article_svr_proto_goTypes,
		DependencyIndexes: file_blog_article_svr_proto_depIdxs,
		EnumInfos:         file_blog_article_svr_proto_enumTypes,
		MessageInfos:      file_blog_article_svr_proto_msgTypes,
	}.Build()
	File_blog_article_svr_proto = out.File
	file_blog_article_svr_proto_goTypes = nil
	file_blog_article_svr_proto_depIdxs = nil
}
